### ISSUE TITLE
Initial Rendering Performance Issues

### ISSUE THREAD

**Issue by a15n** [sir-dunxalot/ember-tooltips#100]
In our app we use tooltips a lot. On some pages there may be dozens of tooltips at a time (sometimes more if we use tables). We saw performance issues when a page or block of code was initially rendered with many tooltips within it because it would lag while each tooltip positioned and rendered itself, even if the tooltips were initially invisible.

In our app we also created a super simplified way to put in a tooltip called {{z-tooltip}}. This encapsulates an info icon and the corresponding tooltip component. You could pass any ember-tooltips related params to the wrapper component and it would pass them through to the `tooltip-on-component` component. 

<img width="696" alt="screen shot 2016-10-14 at 8 04 48 am" src="https://cloud.githubusercontent.com/assets/7050871/19392270/efa5ddb0-91e4-11e6-8a3a-145c43258eba.png">

We fixed the slow load times by "lazy loading" the `tooltip-on-element` within {{z-tooltip}}. Essentially we delay the insertion, rendering, and positioning of the tooltip until someone interacts with the target element (the question icon). We did this with some complex interaction handling and interaction mimicking after the tooltip was rendered. The result is a `tooltip-on-element` that only renders itself after the user has interacted with the icon using a mouseEnter, click, or focusin.

```
import Ember from 'ember';
import template from '../templates/components/z-tooltip';

export default Ember.Component.extend({
    tooltipText: null,
    tooltipClassNames: null,

    // default ember-tooltip options
    delay: 0,
    delayOnChange: true,
    duration: 0,
    effect: 'slide', // fade, slide, none
    event: 'hover', // hover, click, focus, none
    hideOn: null,
    role: 'tooltip',
    side: 'top',
    showOn: null,
    spacing: 10,
    tabindex: '0', // A positive integer (to enable) or -1 (to disable)
    isShown: false,
    keepInWindow: true,

    tagName: 'span',
    template: template,

    _shouldRenderTooltip: Ember.computed.or('isShown', 'hasUserInteracted'),

    willDestroyElement() {
        this._super(...arguments);

        const $tooltipIcon = this.$().find('.js-z-tooltip-icon');
        $tooltipIcon.off('mouseenter click focusin');
    },

    hasUserInteracted: false,
    actions: {
        recordUserInteraction(event) {
            if (!this.get('hasUserInteracted')) {
                this.set('hasUserInteracted', true);

                Ember.run.next(() => {
                    this.$().find('.js-z-tooltip-icon').trigger(event.type);
                });
            }
        }
    },
});
```

```
{{#atoms/info-icon
    classNames='z-tooltip-icon js-z-tooltip-icon'
    mouseEnter=(action 'recordUserInteraction')
    click=(action 'recordUserInteraction')
    focusIn=(action 'recordUserInteraction')
    tabindex=tabindex
}}
    {{#if _shouldRenderTooltip}}
        {{#tooltip-on-component
            effect=effect
            delay=delay
            delayOnChange=delayOnChange
            duration=duration
            effect=effect
            event=event
            hideOn=hideOn
            role=role
            side=side
            showOn=showOn
            spacing=spacing
            tabindex=tabindex
            isShown=isShown
            keepInWindow=keepInWindow
            classNames=tooltipClassNames
        }}
            {{#if hasBlock}}
                {{yield}}
            {{else}}
                {{tooltipText}}
            {{/if}}
        {{/tooltip-on-component}}
    {{/if}}
{{/atoms/info-icon}}
```

I don't know how it would work but it would be amazing if we could make the components in this library lazy load by default, similar to the solution with our {{z-tooltip}}.

**Comment by andrew-zenefits** [comment]
Update: we've introduced a `lazy-tooltip-on-element` in our code base at Zenefits and it has improved load times. We're investigating with `lazy-popovers` but all signs are currently positive.

I'll start working on a PR for this soon.

**Comment by a15n** [comment]
Update: we've introduced a `lazy-tooltip-on-element` in our code base at Zenefits and it has improved load times. We're investigating with `lazy-popovers` but all signs are currently positive.

I'll start working on a PR for this soon.

**Comment by a15n** [comment]
PR is coming along here. Still a lot to do https://github.com/sir-dunxalot/ember-tooltips/pull/104
