### ISSUE TITLE
2.1.0 changes break component tests that previously worked

### ISSUE THREAD

**Issue by JoshSmith** [sir-dunxalot/ember-tooltips#101]
As you can see in this PR https://github.com/code-corps/code-corps-ember/pull/588/files, `ember-tooltips` introduced a breaking change in `2.1.0` that makes the following tests fail: https://github.com/code-corps/code-corps-ember/blob/develop/tests/integration/components/project-category-item-test.js#L51-L54

I'm not quite sure why, or if perhaps there's a better way to be testing altogether, but this does seem to hint at some sort of regression or backwards compatibility problem.

**Comment by sir-dunxalot** [comment]
The ember-tooltip tests [here](https://github.com/sir-dunxalot/ember-tooltips/blob/master/tests/integration/components/show-on-test.js#L23) use `trigger('mouseover');` instead of `trigger('mouseenter')`. I wonder if the fix, which requiring a change on your end, is that simple.

@a15n, off the top of your head do you know of a change that might prevent an assertion like the following from failing?

```js
run(() => {
  this.$('li').trigger('mouseenter');
});

assert.equal(this.$('.ember-tooltip').attr('aria-hidden'), 'false');
```

The assertion matches this addon's test helpers like [assertShow](https://github.com/sir-dunxalot/ember-tooltips/blob/master/tests/helpers/sync/assert-visibility.js#L3).

**Comment by JoshSmith** [comment]
@sir-dunxalot per a comment from @begedin:

> From what I can tell, what caused the tests to fail was that we were checking for presence of the `ember-tooltip-target` class on the `li`. This has changed to `ember-tooltip-or-popover-target`. Once I updated the tests, everything passes again.

Let me know if we should be relying on a class API that's less likely to churn.

**Comment by a15n** [comment]
I'm glad you were able to figure out a fix. That was my fault for not communicating the class name changes more clearly. That's something we should do in the release notes.

And moving forward we will be keeping the `ember-tooltip-or-popover-target` class so you can rely on that. If there is a future instance when we decide to replace a class name (or any other property) we will add a deprecation warning that'll last until the next big version.

PS: Here is the commit in which I changed the `classPrefix` from `ember-tooltip` to `ember-tooltip-or-popover`. Tether uses the classPrefix and adds a `-target` to it. https://github.com/sir-dunxalot/ember-tooltips/pull/92/commits/9dc2fc76909c5560b9be16b24d97c4a2ce148cba

**Comment by sir-dunxalot** [comment]
@JoshSmith Are we all set with a fix on your end now?

I think a good sustainable fix for this library will be documenting the [test helpers](https://github.com/sir-dunxalot/ember-tooltips/blob/master/tests/helpers/sync/assert-visibility.js) and making them publicly available for use in developers' own libraries. I have added #102 to track this.

**Comment by JoshSmith** [comment]
@sir-dunxalot great! I was going to suggest just that! So I'm glad to see it.
