### ISSUE TITLE
had to visibility: hidden

### ISSUE THREAD

**Issue by SirZach** [sir-dunxalot/ember-tooltips#107]
I was using tooltips on a cell per row and the tooltip of the row below prevented the mouse-over to show the tooltip on the row I was hovering on. 

I ended up doing

```
.ember-tooltips {
 &[aria-hidden='true'] {
    visibility: hidden;
  }
}
```

To prevent the tooltip below from blocking the hover. Not sure if it's something you want to add to the core CSS but figured I'd share the experience.

**Comment by sir-dunxalot** [comment]
Thanks for the heads up, Zach. We'll look into this. Are you able to share the code of the page or a URL?

**Comment by SirZach** [comment]
```hbs
<table>
  {{#each model as |m|}}
    <tr>
      <td>
        <a href='/some-link'></a>
        {{#tooltip-on-element}}This links somewhere{{/tooltip-on-element}}
      </td>
    </tr>
  {{/each}}
</table>
```

Just a standard table structure should be able to reproduce this. I think in this scenario, it would be great if `tooltip-on-element` only created one div instead of a div for every instance of it with fixed positioning to less the dom troubles.

**Comment by a15n** [comment]
@SirZach I think you'll be interested in the perf work going on [here](https://github.com/sir-dunxalot/ember-tooltips/issues/100) and [here](https://github.com/sir-dunxalot/ember-tooltips/pull/104)

**Comment by SirZach** [comment]
@a15n great stuff! I am, in fact, interested :)

**Comment by dodeja** [comment]
Yeah +1 on this. `Opacity 0` causes the element behind to be blocked in IE10 (tested). If you have an input and the popover/tooltip happens to be on top of it, focus on the input is blocked.

**Comment by sir-dunxalot** [comment]
@dodeja Did `visibility: hidden;` work for you in IE10?

**Comment by a15n** [comment]
We need to find a solution that (1) doesn't block the elements behind, (2) maintains the visual effect of fading, and (3) is supported in modern browsers.

Right now we use a combination of `pointer-events` and `opacity`. We need opacity for the fading effect. I think we can achieve all 3 criteria with a combination of `display` and `opacity`.

`visibility` may also be appropriate.

@dodeja and @SirZach could you look into this? Thanks for your help so far!

**Comment by sir-dunxalot** [comment]
I tired to fix this tonight but wasn't able to come up with a working solution. If anyone has any ideas, a PR would be much appreciated.

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
