### ISSUE TITLE
passing classNames to tooltip-on-element doesn't work anymore

### ISSUE THREAD

**Issue by SirZach** [sir-dunxalot/ember-tooltips#112]
Just upgraded to 2.4.0 and now passing `classNames` into `tooltip-on-element` doesn't add that class to the div.

```hbs
{{#tooltip-on-element
   side="right"
   tooltipIsVisible=true
  event="none"
  classNames="got-it"
}}
   Some text
{{/tooltip-on-element}}
```

**Comment by a15n** [comment]
The 2.4.0 upgrade turned `tooltip-on-element` into a tagless component. I added the ability to "pass through" `class`, and `id`. But I think I forgot to add pass-through coverage for `classNames`. I think we would also may need to support classNameBindings, attributeBindings, etc.

@SirZach can you look into this and see if passing through classNames and the other dynamic properties works? Thanks

https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/templates/components/lazy-render-wrapper.hbs#L1

**Comment by a15n** [comment]
Also here is the PR that introduces the ability to extend `tether-tooltip-on-element`. 

https://github.com/sir-dunxalot/ember-tooltips/pull/110

**Comment by SirZach** [comment]
Ok, I think I can get to this today.

**Comment by sir-dunxalot** [comment]
@a15n #110 doesn't fix this issue, correct?

**Comment by andrew-zenefits** [comment]
110 does not fix the issue

**Comment by a15n** [comment]
110 does not fix the issue

**Comment by SirZach** [comment]
@a15n how do you want the PR submitted? I forked the repo but not sure if i should commit my changes on a branch or if master is fine and if i should update package.json or not...

**Comment by SirZach** [comment]
went for it...we'll see what you think!

**Comment by a15n** [comment]
addressed with https://github.com/sir-dunxalot/ember-tooltips/issues/133
