### ISSUE TITLE
Passing text through a property to be able to use inline components

### ISSUE THREAD

**Issue by ChrizzDF** [sir-dunxalot/ember-tooltips#115]
Hi guys,

I really enjoy using this addon and I would never ever miss it again! =)

I'm just wondering why there isn't a property to pass the text of a tooltip into the component.
I often use it as follows:
```
{{#tooltip-on-element}}
  Create
{{/tooltip-on-element}}
```

At this point I think the following approach would be really nice to have:

`{{tooltip-on-element text="Create"}}`

This is so much shorter and easier to maintain. Of course I could do this by extending the component but I think this is so fundamental and beneficial that it would be cool if it comes out of the box!

What do you guys think?!

**Comment by sir-dunxalot** [comment]
Totally agree! This would have very low overhead on the repo but would make the dev experience friendly. I'd accept a PR but we can also plan to add it in the future.

**Comment by sir-dunxalot** [comment]
@a15n I imagine you would use this functionality a lot?

**Comment by a15n** [comment]
I like this improvement.

We use something similar and the parameter has been very helpful

**Comment by ChrizzDF** [comment]
Wow, that escalated quickly! 😃 
I saw your implementation and this is so cool.

In the future we can think about having the same for popovers like `{{popover-on-element content=product.description}}`.

Would be the same benefit I think.

Thanks again for implementing this feature so quickly!

Greets from Germany!

**Comment by sir-dunxalot** [comment]
Sounds good for popover - I avoided that for now because I didn't want to deal with escaping HTML when text will suffice for now. We can keep that in mind for the future.

I'm glad this helps you though. A release will be made soon!
