### ISSUE TITLE
Actions on tooltip are triggered twice in test on click()

### ISSUE THREAD

**Issue by YvesYuen** [sir-dunxalot/ember-tooltips#118]
Hi there! 

Some of my tests are failing when using a tooltip with lazy loading combined with an action as follows:
```
<a href="#" class=".js-glue-show-modal" {{action 'showModal'}}>
    <i class="zmdi zmdi-delete"></i>
    {{#tooltip-on-element}} Delete {{/tooltip-on-element}}
</a>
```

The test was failing because the action `showModal` is getting triggered twice the first time `click('.js-glue-show-modal')` is called. This results in 2 modals on the DOM instead of one. 

Tests are passing with `enableLazyRendering` set to false.

Briefly talked with @a15n and he indicated that  https://github.com/a15n/ember-tooltips/blob/c82b8053704c58b95e7e224c628c15ce4beab84e/addon/components/lazy-render-wrapper.js#L134 might be the culprit.

**Comment by sir-dunxalot** [comment]
@a15n Does #114 fix this?

**Comment by a15n** [comment]
Yes I believe 114 will fix it. I have added a test for this. https://github.com/sir-dunxalot/ember-tooltips/pull/114/files#diff-d320863fe14368780962f48a86ff2044R54

@YvesYuen when this lands can you confirm that this fixes your test in your repo?

**Comment by sir-dunxalot** [comment]
I am closing this unless we hear that #114 did not fix this bug.
