### ISSUE TITLE
Can visual effects (transitions) be disabled?

### ISSUE THREAD

**Issue by ChrisLincoln** [sir-dunxalot/ember-tooltips#121]
I have an application where I am using this component to show tool tips for a visualization of a large collection of tightly-spaced-horizontally elements. Each element has unique tool-tip info to present. 

As the mouse is passed left and right over the elements, the animation effect of having the callout pop-out from center and then slide up is rather visually jarring in this particular instance.

Is there a convenient way I can disable the styling that is making that animated transition occur so that the tooltip just renders immediately to its final resting spot? I can see where the sliding/fading is happening in the CSS, but I am a webkit-transition noob.

**Comment by a15n** [comment]
https://github.com/sir-dunxalot/ember-tooltips#effect

**Comment by ChrisLincoln** [comment]
Sorry! I did RTFM, I just missed it!

**Comment by a15n** [comment]
No worries. Hope you enjoy the addon
