### ISSUE TITLE
Glimmer 2 DOMException for popover components

### ISSUE THREAD

**Issue by jordpo** [sir-dunxalot/ember-tooltips#122]
With Ember 2.10, an exception is thrown if you are wrapping a popover component in an if block. It seems related to this issue:

https://github.com/yapplabs/ember-wormhole/issues/66

We are getting around it by wrapping the popover- component in a div.

**Comment by a15n** [comment]
LGTM

@sir-dunxalot do you approve?

**Comment by sir-dunxalot** [comment]
Was that meant to be a comment on #176? If so, yes.

**Comment by a15n** [comment]
haha yes it was

**Comment by maxfierke** [comment]
Addressed in 2.11.1.
