### ISSUE TITLE
Release text-property as 2.4.3

### ISSUE THREAD

**Issue by alvinvogelzang** [sir-dunxalot/ember-tooltips#123]
I see the PR https://github.com/sir-dunxalot/ember-tooltips/pull/116 about the text-property is merged. Is there a reason why this enhancement isn't released as a new patch?

To me, it was a bit confusing reading the master docs in github. With ember install ember-tooltips version 2.4.2 was installed where the text-property isn't available.

**Comment by sir-dunxalot** [comment]
I have just released `2.4.3` with the text property. Thank you for raising the issue.
