### ISSUE TITLE
close popover in javascript using hide() won't reopen the popover again

### ISSUE THREAD

**Issue by gmisa** [sir-dunxalot/ember-tooltips#127]
Hi, i need to put a close button inside the popover and call an action on the component

`actions: {
    closePopover() {
      $('.my__popover').hide();
 }`

however when I try to click the hyperlink to reopen the popover, it won't open anymore.

`{{#popover-on-element side="right" event="click" keepInWindow=false class="my__popover" }}
<a class="popover-close" {{action 'closePopover'}}></a>
{{/popover}}
`

Is there a proper way to close the popover in Javascript?  

Thanks

**Comment by sir-dunxalot** [comment]
Hi @gmisa, I believe you are looking for the `hide` action, which is documented [here](https://github.com/sir-dunxalot/ember-tooltips#popover-on-element).

You use it as follows:

```
{{#popover-on-element as |popover|}}
  Click <button {{action popover.hide}}>here</button> to hide the popover
{{/popover-on-element}}
```
