### ISSUE TITLE
ember-tooltips is broken in ember 2.10.1

### ISSUE THREAD

**Issue by hoboman313** [sir-dunxalot/ember-tooltips#129]
Everything works fine with ember 2.10.0. Upgrade to 2.10.1 and I get
```
Assertion Failed: An action named 'hide' was not found in <...@component:tooltip-on-element::ember12751>
```

**Comment by andrew-zenefits** [comment]
which version of ember-tooltips are you using? I think I've fixed this in 2.5.0

**Comment by hoboman313** [comment]
I'm on 2.5.0

**Comment by andrew-zenefits** [comment]
mmmmm tests are passing up through ember-canary https://travis-ci.org/sir-dunxalot/ember-tooltips

We need to add specific LTS support but it seems like this should be working through canary. Could you try `nombom`? The tooltip-on-element component definitely has a hide action

tooltip-on-element extends lazy-render-wrapper

https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/components/lazy-render-wrapper.js

**Comment by hoboman313** [comment]
@andrew-zenefits My mistake. Forgot that yarn shrinkwraps. I was not on 2.5.0 and it looks like the issue is fixed now.
