### ISSUE TITLE
document text property

### ISSUE THREAD

**Issue by iezer** [sir-dunxalot/ember-tooltips#136]
text property works instead of block form but it's not documented.

**Comment by sir-dunxalot** [comment]
The text property is shown [in the readme](https://github.com/sir-dunxalot/ember-tooltips#tooltip-on-component) so are you asking that we add it to the [options section](https://github.com/sir-dunxalot/ember-tooltips#options)?

**Comment by sir-dunxalot** [comment]
When I fix this I will also make the following improvement to the readme: highlighting the code in [the popover section](https://github.com/sir-dunxalot/ember-tooltips#popover-on-element).
