### ISSUE TITLE
bug with event delegation when the app specifies a rootElement

### ISSUE THREAD

**Issue by humanchimp** [sir-dunxalot/ember-tooltips#141]
Hello!

I found an apparent bug in this addon. I was able to reproduce the problem in a [minimal demo app](https://github.com/lytics/ember-tooltips-bug-app). I will try to put together a PR to fix the problem. In the meantime, I'd be interested in hearing anything you folks might have to say about it, especially if there is a reason that my proposed solution will not work.

Thanks!

## steps to reproduce

I created an app that demonstrates this bug. You can either [clone the demo app](https://github.com/lytics/ember-tooltips-bug-app), or...

1. Set up an app that uses ember-tooltips and specifies a `rootElement`.
1. Make a couple of routes and templates that have the `{{popover-on-element}}` component. Inside the popover, put a `{{link-to}}` component.
1. On one of the templates, wrap the popover with a div with the style attribute set to `position:absolute`. Wrap the other popover in a plain div (or specify `position:static`).
1. Override the stylesheet with `.ember-popover { pointer-events:all; }` to make the link in the popover clickable.
1. Try clicking each of the links.

## expected behavior

The `{{link-to}}`s work normally.

## actual behavior

In the case of the popover that has the `position:absolute` parent, the router does not intercept the event when the link is clicked, and the link defaults to native behavior, which is to follow the link, which in turn causes the ember app to reload.

In the case of the demo app, I added an `onbeforeunload` trap to make the reloading problem more obvious.

## apparent problem

Apparently what is happening here is that the main ember event listeners that are used for event delegation are attached at the `rootElement`, but when the popover is attached to a `position:absolute` element, the tooltip itself gets appended to the `body`, and when events bubble up, nothing handles them, since the tooltips are not children of the root element

## proposed solution

Attach the tooltip elements to the `rootElement` instead of attaching them to the body, so that when the events bubble up, ember can handle them.

**Comment by sir-dunxalot** [comment]
I have started work on this issue on the [attach-events-to-root-element branch](https://github.com/sir-dunxalot/ember-tooltips/tree/attach-events-to-root-element).

**Comment by sir-dunxalot** [comment]
Fixed by [2.9.0-beta.0](https://github.com/sir-dunxalot/ember-tooltips/releases/tag/2.9.0-beta.0).
