### ISSUE TITLE
Namespace for CSS classNames

### ISSUE THREAD

**Issue by alegscogs** [sir-dunxalot/ember-tooltips#15]
Just a quick suggestion: CSS classNames like 'right', 'left', 'in', and even 'tooltip' are pretty broad and can easily conflict with an existing codebase. Fwiw, in our case, many of these classNames are already widely used utility classes in our app. It would be great to have a simple namespace prefixed to all of them, so they become 'ember-tooltips-right', 'ember-tooltips-left', etc., or something similar. Thanks for sharing this cool lib.

**Comment by sir-dunxalot** [comment]
Thanks for the issue. I agree with the conflict happening too easily. The class names are part of the [darsain/tooltips](https://github.com/darsain/tooltip) library, which sits under this addon. The options to customize the classes like `right`, `left`, and `in` are pretty limited and when they can be changed the css has to be manually changed.

I'll look into a way to make custom class names maintainable. We might have to accept manually updating the dependency code with every release but I could live with that! Haha.

**Comment by sir-dunxalot** [comment]
This has been fixed with release `1.0.0`: https://github.com/sir-dunxalot/ember-tooltips/releases/tag/1.0.0

All classes are prefixed by `tooltip-`.
