### ISSUE TITLE
Improve code conventions and linting

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-tooltips#151]
Our addon follows some code conventions loosely. Parts of the code are messy and inconsistent with one another. We should tidy up the code (conventions TBD) whilst using something like [ember-cli-eslint](https://github.com/ember-cli/ember-cli-eslint) to make it easy for contributors to work with our chosen code conventions.

**Comment by sir-dunxalot** [comment]
@a15n What do you think? I have avoided adding comments for code conventions in PRs but I'd like to improve consistency. I don't think this is a big issue and am fine if we don't want to focus on styling right now (we can close this issue without making any changes because this is a rather opinionated improvement and not a functionality addition).

**Comment by a15n** [comment]
I think eslint is a great idea. Can we do this before 3.0.0?

**Comment by sir-dunxalot** [comment]
Great. I have added linting to the pre-3.0 checklist in #109.

**Comment by sir-dunxalot** [comment]
I have begun work on this on the [code-linting](https://github.com/sir-dunxalot/ember-tooltips/tree/code-linting) branch.

**Comment by sir-dunxalot** [comment]
Fixed by #154
