### ISSUE TITLE
Package.json warning in development

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-tooltips#152]
The following warning is shown multiple times when the developer runs `ember s` on the addon locally:

> ember-hash-helper-polyfill is not required for Ember 2.3.0 and later, please remove from your `package.json`.

We should remove `ember-hash-helper-polyfill` from the addon's `package.json` file.

**Comment by a15n** [comment]
IIRC I added this to support the hash polyfill needed for pre 2.3 versions. We need it to support the [hide action](https://github.com/sir-dunxalot/ember-tooltips/blob/2dec625c4791be360dbb2e216419681c18bf8e31/addon/templates/components/tether-popover.hbs) in popovers.

https://github.com/cibernox/ember-hash-helper-polyfill

We need to keep it in pre 2.3.0 but if there is a way to remove it from >= 2.3.0 builds that would be good.

**Comment by sir-dunxalot** [comment]
We could require pre-2.3 Ember apps to install it as a peer dependency.

**Comment by a15n** [comment]
That sounds reasonable, I'd be good with that approach

**Comment by sir-dunxalot** [comment]
Ok, I'm going to make this a 3.0 feature (given the breaking nature of the update) unless you say otherwise. Added to #109.

**Comment by sir-dunxalot** [comment]
Fixed by #272.
