### ISSUE TITLE
unable to use popover in IE11 (windows 8.1)

### ISSUE THREAD

**Issue by ktelles** [sir-dunxalot/ember-tooltips#158]
we're having a problem where the popover appears correctly but when you click on it it interacts with the content underneath it, instead of the popover itself. this is on IE11 (windows 8.1). thanks so much!

![bug](https://cloud.githubusercontent.com/assets/22331782/21736422/6fff7e76-d425-11e6-9c2c-9a7f68d50da5.gif)

**Comment by a15n** [comment]
https://github.com/sir-dunxalot/ember-tooltips/pull/159

**Comment by sir-dunxalot** [comment]
Fixed by `2.7.3`.
