### ISSUE TITLE
Canary support

### ISSUE THREAD

**Issue by mschinis** [sir-dunxalot/ember-tooltips#16]
Hello,
The current build fails on canary. As the ember team is working towards the final 2.0.0 release, it would be good if we had support for canary.

Thanks,
Michael

**Comment by sir-dunxalot** [comment]
Thanks for the issue - very valid. I'll look into it and see what's going on.

**Comment by sir-dunxalot** [comment]
This should be fixed with #22, which was released as `v0.5.0` this evening.
