### ISSUE TITLE
Travis badge in demo app doesn't track master

### ISSUE THREAD

**Issue by sir-dunxalot** [sir-dunxalot/ember-tooltips#161]
The demo app has a travis badge on the index route. This badge isn't restricted to `master` branch and so it shows this addon's build as failing when the latest build fails (regardless of what branch it was). The travis badge should just track the master branch.

**Comment by sir-dunxalot** [comment]
Both the readme and the demo app should be updated to use the Travis badge at `https://travis-ci.org/sir-dunxalot/ember-tooltips.svg?branch=master`.

**Comment by a15n** [comment]
This PR changes the `data-canonical-sc` to those URLs. Not sure if that's all that is needed. I checked on localhost and the demo page hadn't been updated, but the README had. 

It may be a caching issue: wemay have to go through these steps to update it https://help.github.com/articles/about-anonymized-image-urls/

https://github.com/sir-dunxalot/ember-tooltips/pull/172
