### ISSUE TITLE
Multiple popovers don't hide as expected

### ISSUE THREAD

**Issue by a15n** [sir-dunxalot/ember-tooltips#164]
If multiple popovers are hovered into and out of in this scenario then the popovers don't hide as expected....

```
{{#each someArray as |element|}}
  <div>
    {{popover-on-element
      	event="hover"
	effect="fade"
	targetAttachment="top right"
	attachment="top left"
	spacing=0
	hideDelay=10
        enableLazyRendering=true
    }}
  </div>
{{/each}}
```

![sticking-popovers](https://cloud.githubusercontent.com/assets/7050871/21831680/6d5e6460-d75a-11e6-812f-25f496b2f190.gif)

@reidzen and I debugged this and it turns out that the `ember.run` executions on [this line](https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/components/tether-popover-on-element.js#L131) were being queued up and only executing after the last `ember.run` was called. It seems to be behaving like a throttle instead of a setTimeout. Changing that line to a setTimeout fixed the issue locally but I'm not sure that's the ideal fix.

**Comment by a15n** [comment]
@reidzen I tried reproducing this locally but couldn't under the following scenarios...

```
{{#popover-on-element
	event="hover"
	effect="fade"
	spacing=0 
	hideDelay=10 // or 1000
	enableLazyRendering=true 
	side="right"
}}
	some text
{{/popover-on-element}}
```

Is it possible that this is due to the complexity of the page? I need to be able to reproduce this locally so I can design a test that fails in the repro scenario. Could you clone the repo and try to design a scenario in which this fails? I'd recommend using the `/acceptance` URL as a sandbox. Thanks

### hideDelay=10
![hidedelay 10](https://cloud.githubusercontent.com/assets/7050871/22178012/66650f7c-dfe0-11e6-8f49-9ea16b3678df.gif)

### hideDelay=1000
![hidedelay 1000](https://cloud.githubusercontent.com/assets/7050871/22178013/666944c0-dfe0-11e6-8c77-08497e808f90.gif)

**Comment by sir-dunxalot** [comment]
This issue is out-of-date because ember-tooltips `3.0.0` has been released. `3.0.0` brings significant improvements to reliability, simplicity, and extendability.

You can upgrade by running `ember install ember-tooltips` and following [the migration guide](https://github.com/sir-dunxalot/ember-tooltips/blob/master/UPGRADING-3.x.md).

If you see this issue reappear or experience any other bugs, please [open an issue](https://github.com/sir-dunxalot/ember-tooltips/issues/new).
