### ISSUE TITLE
Remove hard-coded font-family for .ember-tooltip and .ember-popover

### ISSUE THREAD

**Issue by nagits** [sir-dunxalot/ember-tooltips#167]
`.ember-tooltip` should inherit font-family by default. For now, `body, html { font-family: 'xxx' }` in my app is not applied to `.ember-tooltip`, and it seems to me strange.
(https://github.com/sir-dunxalot/ember-tooltips/blob/2e01e9e59cc175226e0fc638ac4d185522c4795a/addon/styles/addon.scss#L9)

**Comment by a15n** [comment]
seems reasonable to me. In our app we have to override font-family to inherit. @sir-dunxalot what do you think?

**Comment by sir-dunxalot** [comment]
Let's set `font-family: inherit;` and we'll add a font (or sans-serif) to the dummy app to make the tooltips look indicative of how they will in a consuming app.

**Comment by sir-dunxalot** [comment]
Fixed by #175
