### ISSUE TITLE
[Question] Is there any option to reload tooltips?

### ISSUE THREAD

**Issue by jesusda91** [sir-dunxalot/ember-tooltips#182]
For any reason tooltip don't load correctly even with enableLazyRendering in true, i only have a custom css class

**Comment by sir-dunxalot** [comment]
Could you provide some more details (maybe a screenshot or example). I'm not sure exactly what the issue you're describing is.

**Comment by jesusda91** [comment]
When tooltip loads fine looks like this
![image](https://cloud.githubusercontent.com/assets/6879294/22651942/8dbef596-ec52-11e6-9513-064a96de0131.png)

but sometimes don't load and look like this
![image](https://cloud.githubusercontent.com/assets/6879294/22651962/a19f8e0e-ec52-11e6-9123-659688fbdd47.png)

**Comment by sir-dunxalot** [comment]
You can use the `updateFor` property to rerender tooltips. [There is an example in the demo app](http://sir-dunxalot.github.io/ember-tooltips/#async).
