### ISSUE TITLE
DEPRECATION: Ember.View is deprecated.

### ISSUE THREAD

**Issue by matixmatix** [sir-dunxalot/ember-tooltips#19]
Will there be an update of ember-tooltips suitable for Ember 2.0?

**Comment by sir-dunxalot** [comment]
There will soon. I'm a bit swamped with work right now but it's on my list. I'm happy to accept a PR if someone else wants to make the updates in the meantime.

**Comment by sir-dunxalot** [comment]
Fixed by #22
