### ISSUE TITLE
A component or helper named "tooltip-on-component" could not be found

### ISSUE THREAD

**Issue by okachynskyy** [sir-dunxalot/ember-tooltips#197]
Steps:
1) `ember install ember-tooltips` _(package.json: ember-tooltips": "^2.8.2")_
2) Copy this to my index.hbs
```
<div class="some-component">
  Click for more info

  {{#tooltip-on-element event='click' enableLazyRendering=true}}
    Here is the info!
  {{/tooltip-on-element}}
</div>
```
3) App fail: `A component or helper named "tooltip-on-element" could not be found`

ember-cli: "2.12.2"
node 7.9.0
npm 4.2.0

**Comment by DataSweeper** [comment]
did this issue got resolved? @okachynskyy

**Comment by okachynskyy** [comment]
@DataSweeper, Yes, I just reinstall everything :)
