### ISSUE TITLE
Deprecation for _actions

### ISSUE THREAD

**Issue by maprules1000** [sir-dunxalot/ember-tooltips#203]
When using `popover.hide()` a deprecation is triggered: 

> DEPRECATION: Usage of '_actions' is deprecated, use 'actions' instead.

The `hide` function in `lazy-render-wrapper` should be updated to use the new syntax.

**Comment by a15n** [comment]
`_actions` is the 1.13 way of doing this. If we drop 1.13 we can make this change, but this doesn't seem a compelling enough reason to drop 1.13.
