### ISSUE TITLE
Remove dependency on sass

### ISSUE THREAD

**Issue by xdumaine** [sir-dunxalot/ember-tooltips#205]
Hey! First off, thanks for this awesome addon. I would like to request that you remove all dependencies on sass. Our project doesn't use sass, and this is the only addon we use that does. Unfortunately, through no fault of your own, many of us get errors with node-sass and yarn. 

This addon pulls in ember-cli-sass which pulls in broccoli-sass which pulls in node-sass. It's got *very* little sass in this addon. What do you think about just converting the small amount of sass to CSS, and removing the dependency? This would speed up dependency installation, remove a build step, and save *lots* of downloads of all three of those libraries for projects that don't really need them.

**Comment by claudioc** [comment]
Hi,

any plan to release this "fix" any time soon? Maybe in beta.1?

Thanks! :)

**Comment by maxfierke** [comment]
@xdumaine @claudioc this is now done in 2.11.0 (and will apply to the next 3.0.0 release, as well)
