### ISSUE TITLE
Tooltip does not appear on {{paper-select}} where no option has been selected yet

### ISSUE THREAD

**Issue by acgrama** [sir-dunxalot/ember-tooltips#209]
As the title says, the tooltip does not appear on a {{paper-select}} component when no option has been selected yet.
I have tested this in both Chrome Version 59.0.3071.115 and Firefox 54.0 under Ubuntu 17.04, 64 bit.

Hovering on {{paper-select}} component, nothing selected yet -- no tooltip appears:
![paper-select not ok](https://user-images.githubusercontent.com/1415729/27901966-430a0bfa-6234-11e7-9d5d-0f0a710b6e17.jpg)

Hovering on the dropped-down list of options in the component -- tooltip appears:
![paper-select ok](https://user-images.githubusercontent.com/1415729/27901968-431ef632-6234-11e7-8c3a-f14c5b9a3c35.jpg)

For comparison, a {{paper-input}} component without any input shows the tooltip:
![paper-input ok](https://user-images.githubusercontent.com/1415729/27901967-43116f08-6234-11e7-8f26-5b71377b33c4.jpg)

The Handlebars implementation for the select (even tried setting lazy rendering to false, to try it out):
```
{{#paper-select label=(t 'general.startActivity')
                         options=activities
                         selected=selectedStartActivity
                         onChange=(action (mut selectedStartActivity))
                         as |activity| }}
  {{#tooltip-on-component side='bottom' enableLazyRendering=false}}
       TEST TOOLTIP
  {{/tooltip-on-component}}                      
  {{activity.comment}}
{{/paper-select}}

```
and for the input field:
```
{{#paper-input type="number"
                        value=task.settings.timeStartActivity.value
                        onChange=(action (mut task.settings.timeStartActivity.value))}}
  {{#tooltip-on-component side='bottom'}}
   ...
  {{/tooltip-on-component}}                      
{{/paper-input}}
```

**Comment by maxfierke** [comment]
Closing this since there hasn't been any recent activity and both libraries have changed significantly since it was opened. Feel free to comment to re-open if there is still an issue!
