### ISSUE TITLE
Feature request: add to arbitrary element

### ISSUE THREAD

**Issue by jamesarosen** [sir-dunxalot/ember-tooltips#21]
`addon/utils/render-tooltip` takes an element as its first argument.

`addon/mixins/components/tooltips#renderTooltip` always passes `this.get('element')` as that argument.

I'd like to have a tooltip appear on something like `this.$().closest('.tooltip-target')` to have it appear on a parent element that isn't itself an `Ember.Component` that mixes in the `TooltipsMixin`:

```hbs
<div class='tooltip-target'>
  {{my-component tooltip-content="Hello"}}
</div>
```

```js
MyComponent = Ember.Component.extend({
  tooltipTarget: Ember.computed(function() {
    return this.$().closest('.tooltip-target');
  });
});
```

**Comment by sir-dunxalot** [comment]
Would using the `renderTooltip` util be acceptable for this?

For the above example, this would look something like:

```
import renderTooltip from 'ember-tooltips/utils/render-tooltip';

export default Ember.Component.extend({
  tooltipTarget: Ember.computed(function() {
    return this.$().closest('.tooltip-target')[0];
  });

  renderTooltip: Ember.on('didInsertElement', function() {
    renderTooltip(this.get('tooltipTarget'), {
      content: 'Some tooltip content',
    });
  }),

});
```

That's all possible with the latest release.

**Comment by jamesarosen** [comment]
I like it!

**Comment by sir-dunxalot** [comment]
Awesome. Just let me know if it doesn't work exactly how you would like or if you have any other ideas!
