### ISSUE TITLE
2.9.0-beta-0 Could not find module `ember-tether/components/ember-tether` imported from `ember-tooltips/components/tether-tooltip-and-popover`

### ISSUE THREAD

**Issue by FredUK** [sir-dunxalot/ember-tooltips#214]
After running ember install ember-tooltips it installed latest beta version however when using tooltip-on-element an exception is thrown:

```Could not find module `ember-tether/components/ember-tether` imported from `ember-tooltips/components/tether-tooltip-and-popover````

I have tried installing 2.8 and it complained about unmet dependency of ember-tether.

Not sure what I'm doing wrong but as of now I'm unable to use it.

**Comment by sir-dunxalot** [comment]
Fixed by #196.
