### ISSUE TITLE
Error in 3.0.0-beta.x code example for isShown option (and some other typos)

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [sir-dunxalot/ember-tooltips#223]
The comment in the code example in the `3.0.0-beta.x` documentation for [`isShown`](https://github.com/sir-dunxalot/ember-tooltips/tree/remove-tether-dependency#is-shown) states that the tooltip will be bound to the `showTooltip` property, and yet the actual code just passes the value `true`:
```
{{!--Binds the tooltip visibility to the showTooltip property--}}
{{ember-tooltip isShown=true event='none'}}
```

I'm guessing the second line should read:
```
{{ember-tooltip isShown=showTooltip event='none'}}
```

**Update 1:** I've just spotted a typo elsewhere, and didn't feel it was worth raising a new issue for. In the [`hideOn`](https://github.com/sir-dunxalot/ember-tooltips/tree/remove-tether-dependency#hide-on) docs, the last sentence reads:
> This **opeion** does not affect the event the tooltip shows on

**Update 2:** Another typo: In the [`Accessibility`](https://github.com/sir-dunxalot/ember-tooltips/tree/remove-tether-dependency#accessibility) section, the second sentence reads:
> Elements with tooltips are given a `tabindex` attribute and when the element receives focus, the tooltip **with** show.

**Comment by maxfierke** [comment]
Addressed in 3.0.0-beta.4
