### ISSUE TITLE
[3.0.0] Tooltip content is not wormholed on ember-wormhole 0.5.4

### ISSUE THREAD

**Issue by netes** [sir-dunxalot/ember-tooltips#230]
Hi,
After updating to ember-wormhole 0.5.4 tooltip content is not properly wormholed - it shows just under the trigger element, not in the wormhole container. It seems that this is related PR:
https://github.com/yapplabs/ember-wormhole/pull/101

Regards!

**Comment by jamesdixon** [comment]
@netes I'm on wormhole 0.5.2 and I'm not seeing the tooltips wormholed either; they are being rendered next to the trigger as you described. What version were you on previous to upgrading?

**Comment by netes** [comment]
@jamesdixon on 0.5.3 everything is fine.

**Comment by maxfierke** [comment]
This is fixed via a workaround in 3.0.0-beta.3. Thanks for your report!
