### ISSUE TITLE
[3.0 beta] Uncaught TypeError: Cannot read property 'popper' of undefined

### ISSUE THREAD

**Issue by erichonkanen** [sir-dunxalot/ember-tooltips#231]
Just upgraded to 3.0 beta and seeing this error
`Uncaught TypeError: Cannot read property 'popper' of undefined `

```
_hideTooltip() {
      const _tooltip = this.get('_tooltip');

      if (!_tooltip || this.get('isDestroying')) {
        return;
      }

      _tooltip.popperInstance.popper.classList.remove(ANIMATION_CLASS);
```

**Comment by janmisek** [comment]
For me this is happening when delay is enabled.

**Comment by nicksteffens** [comment]
This happens when we have an `esc` keyBinding on `ember-modal-dialog` is pressed. Regardless if the tooltip is on the page components or not.

**Comment by erichonkanen** [comment]
closing since I'm not working on this atm..
