### ISSUE TITLE
`keepInWindow: true` should ensure the tooltip is always visible

### ISSUE THREAD

**Issue by mirague** [sir-dunxalot/ember-tooltips#237]
Given a tooltip that is rendered above or below an element close to the edge of the window, the tooltip should position itself smartly so that the content can be read.

This is the current behaviour:

<img width="195" alt="screen shot 2018-02-09 at 17 26 18" src="https://user-images.githubusercontent.com/178117/36037994-9a34b3b8-0dbe-11e8-9cea-3b75dcc08cab.png">

Code:
```js
{{#tooltip-on-element keepInWindow=true side="top" enableLazyRendering=true delay=200}}
  Hoshiqua <span class="muted">is playing now</span>
{{/tooltip-on-element}}
```

Ideally the arrow should be anchored and the tooltip's body be moved to the left.

**Comment by andreafrost** [comment]
@mirague Try adding `setPin: true`.  I have a PR open for this change here:
https://github.com/sir-dunxalot/ember-tooltips/pull/220

If this ends up working for you, please thumbs up my PR to help convince @sir-dunxalot that it's worth merging in :)

**Comment by mirague** [comment]
It would seem likely that #220 addresses this issue. Thanks @andreafrost!

**Comment by maxfierke** [comment]
Closing in favor of #220. Thanks @mirague !
