### ISSUE TITLE
Tooltip reappears after route transition

### ISSUE THREAD

**Issue by jamesarosen** [sir-dunxalot/ember-tooltips#24]
If I add a tooltip to a link:
```hbs
{{link-to "Somewhere" "some.where" tooltipContent="Go Somehwere"}}
```
then the tooltip shows up when I hover over the link (yay!). When I click the link, the tooltip disappears (yay!). But when I then move the mouse, it reappears (boo!).

I've set a debugger on `Tooltip.prototype.show`. It turns out that the `mouseover` event is getting fired on the `<a>` when it no longer is in the DOM. I think the simple solution is to guard in either `Tooltip.prototype.show` (an upstream library unfortunately) or in `renderTooltip`:

```js
var willShow = tooltip.hidden && jQuery.contains(document, tooltip.element);
```

**Comment by sir-dunxalot** [comment]
Thanks for digging into it. Which version of this addon are you using? `0.5.2` should contain a fix for this issue.

**Comment by jamesarosen** [comment]
We were on 0.4.0. I see 53d3cfb34a5b5012656a62a514d573c95bd9d48e. I'm trying 0.5.2 now :)

**Comment by sir-dunxalot** [comment]
Ok, great. Let me know if the issue still persists.

**Comment by jrjohnson** [comment]
Is it possible to release a fix on the 0.4.x tree that will work with Ember 1.13?  We're still cleaning out deprecations so we can get into 2.0.  Or am I reading the README wrong and 0.5.x will work with ember pre 2.0?

**Comment by sir-dunxalot** [comment]
I removed the compatibility table because 0.5.x should be backwards compatible. What deprecation warnings are you seeing?

**Comment by jrjohnson** [comment]
All deprecations are in my app.  I hadn't even tried 0.5.x - didn't think it was for me.  I will give it a shot, thanks.

**Comment by sir-dunxalot** [comment]
Ok. If there are any problems just let me know.
