### ISSUE TITLE
File not found: \addon.sass Build Error

### ISSUE THREAD

**Issue by tomasz-szymanek** [sir-dunxalot/ember-tooltips#243]
https://github.com/aexmachina/ember-cli-sass#alternative-addon-usage

Lack of obeying this advice is causing my addon to fail after installing ember-tooltips.
Can I ask you to move styles to appropriate place?

**Comment by lamabiker** [comment]
I have the same issue @tomasz-szymanek, my app will build as soon as I change a file though.

**Comment by tomasz-szymanek** [comment]
@lamabiker And how did you changed this? Can you provide detailed info, please? It would be really helpful for me.

**Comment by lamabiker** [comment]
I didn't solve it, I downgraded version to 2.9.0-beta.0

**Comment by Dan-Ste** [comment]
Maybe your problem related to this one
https://github.com/aexmachina/ember-cli-sass/issues/133
I used sass for the `app` styles file. The issue was resolved when I change it to scss.

**Comment by lamabiker** [comment]
It looks like moving the `ember-cli-sass` from `dependencies` to the `devDependencies` could be a nudge in the right direction. Currently working on a fork

**Comment by lamabiker** [comment]
@tomasz-szymanek please ignore my previous comment, the solution is for there to be both a `addon/styles/addon.scss` and a `addon/styles/addon.sass` :)

**Comment by maxfierke** [comment]
Closing, as of 2.11.0 ember-tooltips no longer uses SASS/SCSS
