### ISSUE TITLE
v2.9.2 broken on ember-beta

### ISSUE THREAD

**Issue by jamesarosen** [sir-dunxalot/ember-tooltips#247]
Whenever I use a `tooltip-on-component`, I get

> Error: Assertion Failed: Attempted to call .sendAction() with the action 'onDestroy' on the destroyed object '<dummy@component:tether-tooltip-on-component::ember3418>'.

from [TooltipOnComponent#willDestroy](https://github.com/sir-dunxalot/ember-tooltips/blob/2.9.2/addon/components/tether-tooltip-and-popover.js#L516-L518)

**Comment by mmadsen2** [comment]
I'm not sure if this is the best fix for this, but I was able to resolve this problem by changing `onDestroy` to `onDestroyElement` in tether-tooltip-and-popover.js.

**Comment by maxfierke** [comment]
This is now fixed in master. Will be in 2.10.0 release. Thanks for the report!
