### ISSUE TITLE
Usage of `_actions` is deprecated

### ISSUE THREAD

**Issue by tomasz-szymanek** [sir-dunxalot/ember-tooltips#248]
`DEPRECATION: Usage of `_actions` is deprecated, use `actions` instead. [deprecation id: ember-runtime.action-handler-_actions] 
`
while clicking on <a href {{action popover.hide}}> in popover

**Comment by maxfierke** [comment]
This is now fixed in master. Will be released in 2.10.0. Thanks for the report!
