### ISSUE TITLE
_didUpdateTimeoutLength in case of Ember.testing === true

### ISSUE THREAD

**Issue by olegdovger** [sir-dunxalot/ember-tooltips#249]
https://github.com/sir-dunxalot/ember-tooltips/blob/b87eab25dc41cf5ffd235fb17133ffd97b40d598/app/components/tooltip-on-element.js#L4

How about this?

```
let _didUpdateTimeoutLength = (config.environment === 'test') || (Ember.testing === true) ? 0 : 1000;
```

**Comment by sir-dunxalot** [comment]
This is fixed by #283, which is on the `3.x` branch, soon to be merged into `master`.
