### ISSUE TITLE
Expand push access to others?

### ISSUE THREAD

**Issue by allthesignals** [sir-dunxalot/ember-tooltips#251]
@sir-dunxalot is it possible to grant push access to others? I know you are probably very busy, but I'd hate to have to depend on a random fork for a small fix. Thank you! :)

**Comment by alexlafroscia** [comment]
I'd love to see this expanded too -- I've been banking on my fork for quite some time that improves integration with the run-loop.

**Comment by sir-dunxalot** [comment]
Hi there, I appreciate the nudge. I just opened #261  and am actively looking for a co-maintainer in order to keep this addon up-to-date.

**Comment by sir-dunxalot** [comment]
Hi gents, @maxfierke is up-and-running as a co-maintainer of this project so you should see better stewardship moving forwards. :)
