### ISSUE TITLE
Deprecation warnings on 2.9.2

### ISSUE THREAD

**Issue by rodrigoyoshida** [sir-dunxalot/ember-tooltips#252]
I am getting deprecation warnings when using this addon on 2.9.2 version. It says that the dependencies ember-hash-helper-polyfill and ember-tether need to be upgraded to at least ember-cli-babel 6.6.

**Comment by maxfierke** [comment]
Hi @rodrigoyoshida! This is now fixed in master and will be in the 2.10.0 release. Thanks for the report!

**Comment by jcfinnerup** [comment]
Is it? I still get the error with a fresh install

**Comment by maxfierke** [comment]
@jcfinnerup which `ember-tooltips` release are you using? Could you post the full error message you're seeing?

You may also need to ensure that `"ember-tether": "^1.0.0"` is specified in your application's `package.json`
