### ISSUE TITLE
3.0.0-beta.2 and Engines

### ISSUE THREAD

**Issue by thec0keman** [sir-dunxalot/ember-tooltips#254]
Using 3.0.0-beta.2 and Ember Engines, and [this](https://github.com/sir-dunxalot/ember-tooltips/blob/3.0.0-beta.2/addon/components/ember-tooltip-base.js#L299) lookup to config is failing inside an engine.

In my experience, looking things up inside an engine isn't as reliable as inside an app normally.  I'd suggest migrating to [ember-get-config](https://github.com/patience-tema-baron/ember-get-config).

I'd be happy to make a PR for this change if you are :+1:

**Comment by maxfierke** [comment]
@thec0keman If you're still up for it, I'd be very open to a PR for using `ember-get-config`!

**Comment by sir-dunxalot** [comment]
This is now fixed on the `3.x` branch, which will soon be merged into master.
