### ISSUE TITLE
Merge error: file app.scss exists

### ISSUE THREAD

**Issue by kasunvp** [sir-dunxalot/ember-tooltips#26]
After installing it gives the following build error when `ember s` is run:

Merge error: file app.scss exists in /mnt/EmberCliRamdisk/ember-client/broccoli_merge_trees-input_base_path-RxstezkD.tmp/39 and /mnt/EmberCliRamdisk/ember-client/broccoli_merge_trees-input_base_path-RxstezkD.tmp/42
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.

Removing the addon resolves it. So it's obvious that the above error happens due to this addon.

Ember-cli: 1.13.8
Ember: 1.13.10

**Comment by sir-dunxalot** [comment]
Hmm. I haven't seen this issue with this addon nor any other addon, which all work in a very similar way. Are you able to provide some code I can use to reproduce this?

My first guess would be that `ember-cli-ramdisk` is causing compatibility issues.

**Comment by sir-dunxalot** [comment]
I still haven't recreated this issue. Have you dug into it anymore?

**Comment by sir-dunxalot** [comment]
Let me know if you're able to reproduce this and we can reopen the issue.
