### ISSUE TITLE
3.0.0-beta.2: ember-tooltip-base.js:486 Uncaught TypeError: _tooltip.show is not a function

### ISSUE THREAD

**Issue by theseyi** [sir-dunxalot/ember-tooltips#262]
Attempting to render an ember-tooltip instance in a native HTML element creates the following errors
- ember-tooltip-base.js:486 Uncaught TypeError: _tooltip.show is not a function

- Uncaught TypeError: Cannot read property 'popper' of undefined

```hbs
      <span>
          {{ember-tooltip}}
      </span>
```

**Comment by maxfierke** [comment]
@theseyi I haven't been able to re-produce this on 3.0.0-beta.4. Could you try out 3.0.0-beta.4 with your use case and let us know if you're still seeing this issue?

**Comment by sir-dunxalot** [comment]
@theseyi Try updating to the latest beta release:

`npm install --save-dev ember-tooltips@3.0.0-beta.5`

If that doesn't fix the issue, we can reopen this.
