### ISSUE TITLE
Rendering issues in Safari Tech Preview (Safari 12.1, WebKit 13607.1.1)

### ISSUE THREAD

**Issue by TheJosephBarnes** [sir-dunxalot/ember-tooltips#263]
A bug where moving over tooltip elements too quickly causes the tooltip to become stuck (the `aria-hidden` flag no longer applies changes properly). Bug does not appear to exist in current Safari (or other browsers). 

Example from the demo page, viewed in Safari Tech Preview - 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/10977795/44054090-a515d824-9f0f-11e8-9f07-ee906e0c028c.png">

**Comment by maxfierke** [comment]
@TheJosephBarnes I wasn't able to reproduce this on Safari 12.0 release, so I'm going to assume it was a bug only present in the TP, which was fixed.

Feel free to re-open if you notice it happening again on the release version!
