### ISSUE TITLE
3.0.0-beta.3: some tooltips don’t render or render strangely

### ISSUE THREAD

**Issue by backspace** [sir-dunxalot/ember-tooltips#275]
Hey all, thanks for the renewed push of work on this addon, it’s quite useful for us in `travis-web`! I was trying out the new beta as suggested in Discord and I found at least one set of tooltips that doesn’t render at all, or occasionally renders in a distorted fashion, maybe related to proximity to the viewport edge. An example, which you can try out [here](https://bd-tooltips-3.test-deployments.travis-ci.org/dashboard/builds) if you log in and turn on the “Dashboard” feature flag in your account settings:

![missing-tooltip](https://user-images.githubusercontent.com/43280/45966184-06af2d00-bff0-11e8-958a-2bd5db34b167.gif)

If you look at the [template](https://github.com/travis-ci/travis-web/pull/1813/files#diff-2ef062b5530a7b1795e8ebc728df1bf4), there’s no obvious difference between the invocation of the tooltip that works and the one that doesn’t. Strangeness!

Let me know if I can help in any way to figure this out. 💞

**Comment by maxfierke** [comment]
Hi @backspace, thanks for the report! My first blink is that it might be the same issue or related issue to #225. I'm going to take a look at fixing that tonight, so hopefully I'll know more then!

**Comment by backspace** [comment]
oh wow, thanks for figuring that out, I’m sorry to have misdirected responsibility! 😳

**Comment by maxfierke** [comment]
All good! We'll be sure to document the CSS changes & potential gotchas when writing up the 2.x to 3.x migration docs.

**Comment by maxfierke** [comment]
@backspace 3.0.0-beta.5 (now latest) adds support for passing `popperOptions`. I think something like this _may_ fix the behavior you're seeing without needing a CSS workaround:

`{{ember-tooltips text=tooltipText popperOptions=popperOptions}}`

where `popperOptions` is set to something like this:

```json
{
  "modifiers": {
    "preventOverflow": {
      "escapeWithReference": false
    }
  }
}
```

**Comment by backspace** [comment]
Thanks for the tip! I actually wasn’t able to figure out a good CSS fix for this as there’s some weirdness to add fading for very long strings, so I hope to find another way.

I tried this locally with beta 5 and it didn’t seem to help; I can only see a hint of the tooltip while scrolling:

![tooltip-overflow](https://user-images.githubusercontent.com/43280/47037764-7030e000-d145-11e8-9c81-70c2f18016b7.gif)

I’m semi-off work at the moment and can’t dig too deeply, but I’ll try to find a workaround when I’m back.
