### ISSUE TITLE
Popper.js sourcemap error on 3.0.0-beta.3

### ISSUE THREAD

**Issue by shanicem** [sir-dunxalot/ember-tooltips#277]
I'm trying to upgrade to the 3.0.0-beta.3 version but I get this error when I try to start the server:

`ENOENT: no such file or directory, open '/Users/username/project-name/tmp/source_map_concat-input_base_path-N0GNP8fr.tmp/vendor/popper/popper.js'`

It seems similar to issue #226 

Is this still a known issue?

**Comment by maxfierke** [comment]
@shanicem Thanks for the report! This instance seems a little different, since it can't seem to find `popper.js` rather than `popper.js.map`. Could you post which version of ember-cli you're using and which version of `popper.js` npm has installed? (I think `npm list popper.js` should show the version)

**Comment by shanicem** [comment]
@maxfierke thanks for the quick reply! we're using `popper.js@1.14.4` and `ember-cli@3.3.0`

**Comment by maxfierke** [comment]
@shanicem Unfortunately, I was unable to reproduce this with a newly generated ember 3.3 app, which suggests to me that this might be environmental. I'd suggest clearing `node_modules`, `tmp` and `dist`, and doing an `npm install` from scratch to see if that fixes it.

If you're still seeing the error after that, I'd be curious about what other addons your app is using. Perhaps there's a conflict somewhere!

**Comment by shanicem** [comment]
@maxfierke Thanks for your response. We tried what you suggested above, as well as upgrading to beta.4, but still getting the same issue. We're just going to move to 2.11.1 for now which is working for us. Thanks again for all your help!

**Comment by sir-dunxalot** [comment]
@shanicem This seems like a rare but serious error. Even though `2.11.1` is working for you, it would be very helpful if you could provide some information that @maxfierke or I can use to debug this issue.

Are you able to share your `config/environment.js` and  `ember-cli-build.js` files? Alternatively, if you are able to give access to a repo that has a branch demonstrating this issue, we can look at the issue there.

**Comment by shanicem** [comment]
@sir-dunxalot Unfortunately I can't share them publicly. Would it be possible to send them to you in an e-mail?

**Comment by sir-dunxalot** [comment]
@shanicem, yes of course. I just sent you an email that you can respond to.

**Comment by sir-dunxalot** [comment]
I am also going to investigate whether this issue appears when `popper.js` or `ember-popper` are installed. For example, it has been suggested that this issue is present when `ember-bootstrap` is installed, which uses `ember-popper`.

**Comment by sir-dunxalot** [comment]
I came across a similar issue in another plugin that was solved with an [update for md5](https://github.com/Exelord/ember-initials/pull/57/files). This could be useful or it might be an entirely unrelated fix.
