### ISSUE TITLE
tooltipContent can't handle safeString

### ISSUE THREAD

**Issue by dzena** [sir-dunxalot/ember-tooltips#29]
I'm setting tooltipContent from the translation object (ember-i18n) which returns an SafeString object with the string property, which contains the actual message. 

As a result from the tooltip I get an error message: Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. tooltip/index.js:225

**Comment by sir-dunxalot** [comment]
Thanks for opening the issue. I'm not sure what the standard protocol is around accepting safe strings as properties but I can look into it. Do you have any ideas or a quick workaround in the meantime?
