### ISSUE TITLE
isShown cannot be used to hide() popover

### ISSUE THREAD

**Issue by basicBrogrammer** [sir-dunxalot/ember-tooltips#295]
When isShown changes to true, the popover displays.
When isShown changes back to false, hide() doesn't dismiss the popover. 

Do we know why this line of code was added? 
https://github.com/sir-dunxalot/ember-tooltips/blob/3.x/addon/components/ember-popover.js#L99
hide() is essentially a noop when isShown === false

**Comment by sir-dunxalot** [comment]
The app in question is using ember-tooltips `3.0.0.beta-5`.

This will need to be further investigated since [the test suite is currently passing with this case](https://github.com/sir-dunxalot/ember-tooltips/blob/3.x/tests/integration/components/is-shown-test.js#L23-L27).

**Comment by sir-dunxalot** [comment]
This issue is specific to `{{ember-popover}}` and doesn't exist for `{{ember-tooltip}}`. We will need to replicate the [`isShown` test](https://github.com/sir-dunxalot/ember-tooltips/blob/3.x/tests/integration/components/is-shown-test.js#L23-L27) for popovers to protect against this case.

**Comment by basicBrogrammer** [comment]
The `ember-tooltip` component works fine (above test example from @sir-dunxalot ). 
The `ember-popover` component doesn't hide when isShown === false. See https://github.com/sir-dunxalot/ember-tooltips/blob/3.x/addon/components/ember-popover.js#L99
