### ISSUE TITLE
NPM install causes issues

### ISSUE THREAD

**Issue by bahdvp** [sir-dunxalot/ember-tooltips#316]
Using `npm install` to build and deploy ember-tooltips causes issues with the tooltip text content rendering in the wrong location. If I use `yarn install` to install all packages, this issue goes away for me.

Can anyone else confirm? Addon should largely be package manager agnostic.

**Comment by maxfierke** [comment]
@bahdvp are you talking about when using it an app or when checking out the addon locally?

**Comment by bahdvp** [comment]
Sorry, when using it in an app.

**Comment by maxfierke** [comment]
Do you normally use `npm` or `yarn` with your app? Perhaps the two have different default version resolution strategies? Does it happen with other addons? What version of ember-cli are you using?

**Comment by bahdvp** [comment]
Generally use npm.
Hasn't happened that I've noticed with other addons.
ember-cli 3.5

The issue was temporarily fixed by reverting to 3.0.0-beta.2 which does not appear to present the issue for whatever reason.

**Comment by bahdvp** [comment]
Another dev on the team found that manually installing `ember-wormhole` fixed the issue. Possibly a dependency conflict as other addons were using 5.4.
