### ISSUE TITLE
Compatibility issues between 3.X and other addons (ex: ember-paper)

### ISSUE THREAD

**Issue by panthony** [sir-dunxalot/ember-tooltips#318]
From #309

Dependencies are:

- `ember@3.0`
- `ember-cli-htmlbars@2.0.3`
- `ember-tooltips@3.0.2`
- `ember-paper@v1.0.0-beta.7`

Seems like something goes wrong with paper-tabs @ ember-paper (maybe other addons too).

In an empty template, this crash:

```hbs
{{#paper-tabs selected="tab" onChange=onChange as |tabs|}}
  {{#tabs.tab value="tab"}}
    "hello"
  {{/tabs.tab}}
{{/paper-tabs}}

{{#eachitems as |item|}}
  <div>
    {{item}}
    {{#ember-tooltip}}
      tooltip
    {{/ember-tooltip}}
  </div>
{{/each}}

```

This works:

```hbs
{{#eachitems as |item|}}
  <div>
    {{item}}
    {{#ember-tooltip}}
      tooltip
    {{/ember-tooltip}}
  </div>
{{/each}}

```

This works too:

```hbs
{{#paper-tabs selected="tab" onChange=onChange as |tabs|}}
  {{#tabs.tab value="tab"}}
    "hello"
  {{/tabs.tab}}
{{/paper-tabs}}
```

The behavior is not the same depending on the number of tooltip in the page:

If items has:

- less than 11 elements -> works
- 11 elements -> Uncaught Error: infinite rendering invalidation detected
- 12 elements -> Assertion Failed: Cannot deregister unknown unregistered renderer
- more than 12 elements -> The head node of a wormhole must be attached to the DOM

**Comment by maxfierke** [comment]
@panthony does #320 fix it for you?

**Comment by maxfierke** [comment]
@panthony you may want to try enabling backburner debugging `Ember.run.backburner.DEBUG = true;` and stepping into backburner as per https://guides.emberjs.com/release/configuring-ember/debugging/#toc_errors-within-emberrunlater-backburner to check out the stitched-together stacktrace

**Comment by panthony** [comment]
@maxfierke `Tooltip` is undefined.

And `const tooltip = new Tooltip()` is somehow swallowed somewhere.

And then `willDestroyElement` and there is no `_tooltip` defined.

I'm not quite sure how it fits with the fact that I saw it works with few elements...

**Comment by maxfierke** [comment]
I've been able to reproduce this in production-builds.

It seems to have something to do with sourcemaps, oddly, since everything works as expected if sourcemaps are explicitly enabled for production builds:

```"use strict";

const EmberApp = require("ember-cli/lib/broccoli/ember-app");

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    sourcemaps: {
      enabled: true, // Normally defaulted to `EmberApp.env() !== 'production'`
      extensions: ["js"]
    }
  });

  // ...

  return app.toTree();
};
```

If you're okay shipping sourcemaps in production, that is a workaround that can be used for the time being.

**Comment by panthony** [comment]
@maxfierke I confirm that `3.1.1` fixed my issues.
