### ISSUE TITLE
3.x moving your mouse over and out and over quickly will prevent visibility

### ISSUE THREAD

**Issue by arthur5005** [sir-dunxalot/ember-tooltips#321]
You can see it on the demo page with the first example.
http://sir-dunxalot.github.io/ember-tooltips/

![2018-11-23 15 43 36](https://user-images.githubusercontent.com/697846/48962601-a0cf1b00-ef36-11e8-892a-46fe34d588d7.gif)

**Comment by arthur5005** [comment]
Found the problem. `_tooltip.hide()` doesn't get called synchronously, so it's possible to call `_tooltip.show()` twice before hide gets called (inside the `run.later`) I assume this is so we can wait for the 

https://github.com/sir-dunxalot/ember-tooltips/blob/3baca0509dba8a8f1264351f885240de24f2ee75/addon/components/ember-tooltip-base.js#L480-L504

It's Friday, and I already have a drink in my hand :D. But I imagine we could either:
a) Track when transitions are happening, then call hide/show synchronously in those cases
b) Track the `run.later`s on hide/show and cancel them whenever we hide/show

**Comment by maxfierke** [comment]
I think you're right on the money there! It's on my to-do to add a bit more bookkeeping to our runloop scheduling, given a few recent runloop-related bugs.

Thanks for digging!

**Comment by arthur5005** [comment]
Just added a PR as a suggestion. Works well on our fork.
