### ISSUE TITLE
Allow custom template HTML

### ISSUE THREAD

**Issue by brookjordan** [sir-dunxalot/ember-tooltips#324]
Currently, the tooltip wrapper is, (as far as I can see,) uneditable:
https://github.com/sir-dunxalot/ember-tooltips/blob/8983cd7f8d90d09510aeb94d24fadbcc1bfc7876/addon/components/ember-tooltip-base.js#L321-L324

This is causing issues with our repo on a few fronts:
 - as we also use `Bootstrap` tooltips in other parts of the app this is conflicting and causing CSS conflicts which are a bit of a pain to override and gain control of
 - the rest of our app uses BEM class names and I'm a little disappointed that we'd have to move away from this naming convention

Would it be possible to allow a custom template string to be passed in, keeping the current one as the default so as not to disrupt current users?

**Comment by maxfierke** [comment]
I think the trick with providing a way to customize the template, is that we would need to support insertion of the wormhole element ID and the initial styles and that kind of thing.

I think a less drastic approach that would address these concerns would be simply to better namespace the markup controlled by ember-tooltips and allow specifying additional classes for the arrow and the inner `<div>`. I'd agree that applying `tooltip` is a bit too broad and assumes that `ember-tooltips` is the only tooltip library/implementation on the page. The `tooltip[-arrow,-inner]` classes are just the defaults used by `Tooltip.js` but they can be overridden and we should do that.

**Comment by brookjordan** [comment]
Ok, that will work too.
I've opened a PR for it:
#327
