### ISSUE TITLE
Does order matter when using targetId?

### ISSUE THREAD

**Issue by mnoble01** [sir-dunxalot/ember-tooltips#326]
We are using ember tooltips in a template like so:

```
          {{#ember-tooltip
            popperContainer='body'
            targetId="has-info-tooltip"
          }}
            Tooltip content
          {{/ember-tooltip}}
          {{fa-icon "question-circle" id="has-info-tooltip"}}
```

This fails in Windows 10 IE11 with:
```
Uncaught TypeError: Unable to get property 'add' of undefined or null reference
```

My question is -- does order matter? All the examples you give using `targetId` render the tooltip target first, and then the tooltip.

**Comment by maxfierke** [comment]
@mnoble01 the element with the `targetId` must exist in the DOM before the tooltip is rendered, so it probably does need to come before the tooltip.

One thing you may want to try is giving both elements a wrapper element like this:

```
<span class="js-info-tooltip-target">
  {{#ember-tooltip popperContainer='body'}}
    Tooltip content
  {{/ember-tooltip}}
  {{fa-icon "question-circle"}}
</span>
```

**Comment by mnoble01** [comment]
Yep, the wrapper is also an option that I may try. Curious that the wrong order only causes errors in IE11...

**Comment by mnoble01** [comment]
If anyone is interested, changing the order did not work. The wrapping div did.
