### ISSUE TITLE
In IE11 the x-axis translation on element is getting more than expected

### ISSUE THREAD

**Issue by Skgtouch** [sir-dunxalot/ember-tooltips#331]
"ember-tooltips": "^2.9.2",

{{popover-on-element}}

In chrome the pop up is coming exactly on the target element.
While in IE 11, it's coming around 100px left to target element.

Thanks!

**Comment by maxfierke** [comment]
@Skgtouch could you provide a twiddle or a repo that reproduces this?

**Comment by Skgtouch** [comment]
Solved the issue for handling IE separately.
