### ISSUE TITLE
onHide events fire on all subsequent clicks after tooltip has been hidden

### ISSUE THREAD

**Issue by Allerby** [sir-dunxalot/ember-tooltips#333]
It seems as though the onHide event fires it's action on all subsequent clicks after the tooltip has been hidden.

Behavior can be seen in the twiddle below, here are steps for repro:
1. Open console
2. Hover over the button
3. click anywhere on the page and inspect the console to see the action firing for all clicks on the page

https://ember-twiddle.com/8ec0ece5f26a83f0111c13b337a2559b?openFiles=templates.application.hbs%2C

I might be missing some important config but this seems like a bug?

Thanks for your work :)

**Comment by maxfierke** [comment]
Thanks for the heads up @Allerby! I'll take a look

**Comment by maxfierke** [comment]
Will be addressed by https://github.com/sir-dunxalot/ember-tooltips/pull/338
