### ISSUE TITLE
Can't close the popover using isShown prop modified by clicking button in the popover

### ISSUE THREAD

**Issue by szimek** [sir-dunxalot/ember-tooltips#335]
I've got a simple popover that has "cancel" and "confirm" buttons. When one of these buttons is clicked, I change a value that is assigned to `isShown` prop. However, when I click one of these buttons the popover is not hidden, even though `isShown` is set to `false`. The issue is (most likely) caused by the following check in `hide` method:
```js
if (!this.get('_isMouseInside')) {
  this._hideTooltip();
}
```
When I click the button, the mouse is inside, so `this._hideTooltip();` is not called. It looks like `hide` action explicitly sets `_isMouseInside` to `false` before calling `hide`.

**Comment by maxfierke** [comment]
@szimek could you share your template code invoking `ember-tooltips`?

**Comment by szimek** [comment]
Sure. I'm replacing Bootstrap popover with this library, so maybe there's something messed up there.

_popover-confirm.hbs_
```handlebars
{{#ember-popover isShown=isVisible event="none" side="top" delay=0 delayOnChange=false effect="none" hideDelay=0}}
  <div class="popover-body">
    <p>{{yield}}</p>
    <div class="popover-buttons">
      {{#if cancel-button-label}}
        <button type="button" class="button cancel" {{action "cancel"}}>{{cancel-button-label}}</button>
      {{/if}}

      {{#if confirm-button-label}}
        <button type="button" class="button confirm" {{action "confirm"}}>{{confirm-button-label}}</button>
      {{/if}}
    </div>
  </div>
{{/ember-popover}}
```
I'm then using my `popover-confirm` component like this:
```handlebars
{{#popover-confirm
  isVisible=hasSelectedFile
  onConfirm=(action "sendFileTransferInquiry")
  onCancel=(action "cancelFileTransfer")
  confirm-button-label="Send"
  cancel-button-label="Cancel"
}}
  Do you want to send <strong>"{{filename}}"</strong> to <strong>"{{label}}"</strong>?
{{/popover-confirm}}
```

**Comment by szimek** [comment]
I guess I'll have to figure out another way of setting up and closing these popovers anyway and trigger `onCancel`/`onConfirm` actions *after* the popover is really closed. I'm not sure if it's possible to call an action of a child component (feels kind of hacky), or maybe I could extend `ember-popover` and call `hide` action from another action, though I'm not sure if it's possible as well.

It looks like there's hardcoded `_animationDuration` of [200ms](https://github.com/sir-dunxalot/ember-tooltips/blob/e385c9afaa7622aa241a0bb153f0bf9b3c8f7335/addon/components/ember-tooltip-base.js#L170) that is used when [closing popovers](https://github.com/sir-dunxalot/ember-tooltips/blob/e385c9afaa7622aa241a0bb153f0bf9b3c8f7335/addon/components/ember-tooltip-base.js#L501), so even if I disable the `isMouseInside` check, with the way my code works, the data used by content displayed in the popover is gone before the component disappears :/

**Comment by maxfierke** [comment]
you can call `hide` for the popover component. we support this: https://github.com/sir-dunxalot/ember-tooltips#ember-popover

e.g. you could do something like this to pass through the `ember-popover` `hide` action into your own cancel action

```
{{#ember-popover isShown=isVisible event="none" side="top" delay=0 delayOnChange=false effect="none" hideDelay=0 as |popover|}}
  <div class="popover-body">
    <p>{{yield}}</p>
    <div class="popover-buttons">
      {{#if cancel-button-label}}
        <button type="button" class="button cancel" {{action "cancel" (action 'hide' target=popover)}}>{{cancel-button-label}}</button>
      {{/if}}

     {{! -- blah --!}}
    </div>
  </div>
{{/ember-popover}}
```

This would pass a callback that calls `popover.hide()` to your `cancel` action, which you could then call in your action to control when the hide happens.

You're right, though. That alone does not address the hard-coded animation duration, but you can also pass an `onHide` action to the component, which will get called once the popover or tooltip is fully hidden: https://github.com/sir-dunxalot/ember-tooltips#actions

**Comment by maprules1000** [comment]
@maxfierke That's really useful info to know. Maybe it can be added to the readme on `isShown` as a popover-specific section?

**Comment by maxfierke** [comment]
@maprules1000 I think we should probably fix the bug and make it possible to toggle with `isShown`, just like tooltips, rather than documenting and supporting a convoluted workaround 😛 I'll take a look at doing so this week. Popovers need some love

**Comment by maxfierke** [comment]
Mind taking a look at https://github.com/sir-dunxalot/ember-tooltips/pull/338? It should resolve the issue here with toggling popovers using `isShown`

@szimek One caveat, is that modifying the var tied to `isShown` inside of the popover will cause a double-render error. I'm still looking into why that's happening.

@maprules1000 I added a test & example specifically for the case you're describing
