### ISSUE TITLE
Can't extend / set defaults

### ISSUE THREAD

**Issue by optikalefx** [sir-dunxalot/ember-tooltips#336]
I had the clipping issue when upgrading from 2 -> 3, so I went to set the default for all tooltips to render on the body. But just merely having 

```
import EmberTooltipComponent from 'ember-tooltips/components/ember-tooltip';

export default EmberTooltipComponent.extend({
  effect: 'fade',
  side: 'bottom',
});
```

in existence, causes the tooltip to show an empty popup. 

![image](https://user-images.githubusercontent.com/926885/51863874-29d84900-2310-11e9-86b9-e6a03ea33279.png)

Any idea where I can look for this?

**Comment by maxfierke** [comment]
@optikalefx anything logged in the console / exceptions thrown?

**Comment by optikalefx** [comment]
Here's a twiddle https://ember-twiddle.com/ac75eb9934ee38531a5e31722d25dcde?openFiles=components.ember-tooltip.js%2Ctemplates.components.ember-tooltip.hbs when we attempt to extend with defaults, the tooltip is just empty. If you delete the component files it will work.

I find this to be the case for the 2.x branch as well.

**Comment by optikalefx** [comment]
That works. Thanks! Maybe a docs update would be good.

- Sean

**Comment by maxfierke** [comment]
Added a note to the docs.
