### ISSUE TITLE
Ember-tooltips 3.1.1 - Breaks build Broccoli - popper.js no such file or directory

### ISSUE THREAD

**Issue by FredUK** [sir-dunxalot/ember-tooltips#339]
Similar to #323 but I'm not using workspaces nor using yarn. Also, #323 mentions op issue is fixed in 3.1.1 which is the one I'm trying.

A simple ember install ember-tooltips and then ember serve returns:

The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat 'C:\www\myapp\tmp\source_map_concat-input_base_path-XJhi7ms0.tmp\0\node_modules\popper.js\dist\umd\popper.js

Also tried a manual install of popper.js with `npm install popper.js --save` but still no go.

"ember-cli": "2.6.2",
"ember": "2.8.3",
"ember-tooltips": "3.1.1",

Just wondering if 3.1.1 is not compatible with Ember 2.8 ? I really didn't want to install ember-tooltips 2 due to tether.

**Comment by maxfierke** [comment]
@FredUK ember-tooltips only supports Ember-CLI 2.15+, so you'll need to upgrade your `ember-cli` version (this can be done without upgrading Ember)
