### ISSUE TITLE
3.1.1 lazyRendering is not working anymore

### ISSUE THREAD

**Issue by GerritSommer** [sir-dunxalot/ember-tooltips#340]
I just updgraded from 2.10 to 3.1.1 and made all the changes as recommended.
I am heavily relying on lazyRendering as some tooltips access computed properties, which should only be computed when needed (-> when the popover is shown).

With the new version the content-block of the tooltip seems to be computed when the targetElement is inserted to the DOM.

I made a little twiddle (always wanted to say that), which shows the problem:
https://ember-twiddle.com/e26ba3e4b9bcd7377a757e9cd33b12c0?openFiles=templates.application.hbs%2Ctemplates.components.ember-tooltip.hbs

I am not sure if I missed some new convention on how to use this addon, but I'd appreciate some help.

**Comment by maxfierke** [comment]
@GerritSommer I will refer you to this reply from an earlier issue for now (and I shall update the Upgrading documentation later to include this): https://github.com/sir-dunxalot/ember-tooltips/issues/330#issuecomment-448271612

Please let me know if you have any follow-up questions!

**Comment by GerritSommer** [comment]
@maxfierke 	Oh great, thats exactly what I needed.
Thanks for the info and the addon.
