### ISSUE TITLE
Specifying an overriding css class does nothing

### ISSUE THREAD

**Issue by ChiefBK** [sir-dunxalot/ember-tooltips#345]
According to the documentation it looks like I can add a CSS class to the `ember-tooltip` component:

```
{{ember-tooltip class='tooltip-warning'}}
```

I have a simple CSS class
```
.drive-dashboard__table-tooltip {
  background-color: white;
  color: black;
}
```

And specified this with my component:
```
{{#ember-tooltip class="drive-dashboard__table-tooltip" event="click" side="bottom"}}
          A tooltip for the settings
{{/ember-tooltip}}
```

Which rendered the following:
<img width="196" alt="screen shot 2019-02-20 at 3 39 38 pm" src="https://user-images.githubusercontent.com/4656504/53126544-fe6b0780-3525-11e9-9c56-137023d582f6.png">

No different than the default tooltip CSS.

However if I change the component attributes:
```
{{#ember-tooltip tooltipClassName="ember-tooltip drive-dashboard__table-tooltip" event="click" side="bottom"}}
          A tooltip for the settings
{{/ember-tooltip}}
```
It renders correctly with the overridden CSS class
<img width="195" alt="screen shot 2019-02-20 at 3 42 31 pm" src="https://user-images.githubusercontent.com/4656504/53126738-71747e00-3526-11e9-844b-0c6e542927b4.png">

What is the proper way to override the CSS of the pop-up?

**Comment by maxfierke** [comment]
`class` will only apply to the wrapper element, rather than the actual tooltip element right now, so the `tooltipClassName` approach is the correct way to do this.

There's a pending PR #327, which will hopefully clean this up a bit, and provide a more clear way to specify custom classes
