### ISSUE TITLE
tooltipContent can't be a SafeString

### ISSUE THREAD

**Issue by jamesarosen** [sir-dunxalot/ember-tooltips#35]
https://github.com/sir-dunxalot/ember-tooltips/blob/86f49080abc31b75e252f5e3b3804aa89da4b056/addon/mixins/components/tooltips.js#L208 passes `tooltipContent` directly to `tooltip.content(...)`. This *must* be a plain string; the underlying library doesn't coerce it. If I do the following
```js
someProperty: Ember.computed(function() {
  return Ember.String.htmlSafe('some text');
})
```
```hbs
{{link-to .... tooltipContent=someProperty}}
```
Then I get
> Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

This is notable because [ember-i18n](https://github.com/jamesarosen/ember-i18n) returns all translated strings as SafeStrings.

I have two ideas:

 1. just stringify anything that comes in: `tooltip.content('' + tooltipContent)`
 2. try to understand HTML safety and HTML-escape `tooltipContent` *unless* it's a SafeString

I think (2) is more correct than (1), but it may break some apps.

**Comment by sir-dunxalot** [comment]
Hey James, this should have been fixed by #30 (`^0.5.5`). Can you please confirm which version you are using?

**Comment by jamesarosen** [comment]
We're on 0.5.4, so I bet it will be! I'll reopen with more information if we have problems. Thanks :)

**Comment by sir-dunxalot** [comment]
Sounds good!
