### ISSUE TITLE
Tabindex is missing .

### ISSUE THREAD

**Issue by sakinehmehrabi** [sir-dunxalot/ember-tooltips#352]
http://sir-dunxalot.github.io/ember-tooltips/
tabindex is not using  by default .so we can not use event focus... .

**Comment by maxfierke** [comment]
Thanks! This indeed looks like a bug. We probably just need to be specifying `tabindex="-1"` on our tooltip elements. I'll take a look at this today or tomorrow.

**Comment by sakinehmehrabi** [comment]
Hi,
With customising a component's element it will be work :
`tagName: 'a',
 attributeBindings: ['tabindex'],
 tabindex:'0',`
