### ISSUE TITLE
Vendor JS sourcemaps missing sourcesContent

### ISSUE THREAD

**Issue by les2** [sir-dunxalot/ember-tooltips#354]
Issue #227 appears to be back. Sourcemaps are broken. I have documented the issue with a repo that will reproduce the problem using the latest version of Ember here: https://github.com/les2/soucemap-test-ember-3-9

In short, adding `ember-tooltips` addon causes sourcemaps for vendor to exclude the `sourcesContent` element. This breaks tools such as New Relic Browser, which use `sourcesContent` to unminify JavaScript stacktraces captured in errors (it will not make Network requests to resolve sourcemap, nor is the sourcemap even hosted so that it could).

Relates to https://github.com/sir-dunxalot/ember-tooltips/issues/277

I'm willing to help if you have any pointers.

**Comment by maxfierke** [comment]
thanks for the reproduction @les2! I'll take a look!
