### ISSUE TITLE
Support @ember/optional-features@0.7.0

### ISSUE THREAD

**Issue by andreyfel** [sir-dunxalot/ember-tooltips#355]
@ember/optional-features is locked as a dependency on ^0.6.3. Our app is using ^0.7.0, thus dependency linter gives a test failure for @ember/optional-features.
Maybe we should use less restrictive specification, like "^0.6.0 || ^0.7.0" to support apps with 0.6 and 0.7 versions?

**Comment by maxfierke** [comment]
Hi @andreyfel! thanks for raising this. Was just discussing [in a PR review](https://github.com/sir-dunxalot/ember-tooltips/pull/351#pullrequestreview-233766185) that it might be possible to remove the dependency altogether. I'll be looking into it this week, so stay tuned!
