### ISSUE TITLE
Merge error: conflicting file types: popper.js is a directory [.. but file in]

### ISSUE THREAD

**Issue by omairvaiyani** [sir-dunxalot/ember-tooltips#360]
[This bug](https://github.com/sir-dunxalot/ember-tooltips/issues/339) seems to have re-emerged in 3.3.1.

Latest version of ember. Fixes when I rollback to 3.3.0.

**Comment by maxfierke** [comment]
@omairvaiyani what versions of Ember, Ember-CLI, and popper.js are your app using?

**Comment by alanlalonde** [comment]
Here's the bug output from a build.

> Merge error: conflicting file types: popper.js is a directory in /tmp/broccoli-*hash*/out-118-broccoli_merge_trees_addon_tree_for_ember_bootstrap_vendor but a file in /tmp/broccoli-*hash*/out-164-broccoli_persistent_filter_simple_replace_remove_sourcemap

Using ember-cli 3.9.0 (well aware that 3.10.0 was released three days ago, but builds stopped working yesterday).

**Comment by maxfierke** [comment]
@alanlalonde it looks like you might be using ember-bootstrap?

It seems `ember-bootstrap` depends on `ember-popper`, which also includes `popper.js` as a dependency in its build output. I'm not sure what the runtime result of mixing the two addons is, but we'd probably need to rename our `popper.js` build output to avoid the conflict.

Given the number of people who use `ember-bootstrap` alongside `ember-tooltips`, despite the conflicting tooltip implementations, it's probably work fixing on our end.

**Comment by alanlalonde** [comment]
Yes, the project uses `ember-bootstrap`. While checking my `package-lock.json`, it also shows `ember-popper` uses it. I'm not sure if that dependency comes from `ember-bootstrap` or `ember-tooltips`.

**Comment by maxfierke** [comment]
Both addons copy the dependency into the `vendor` tree for various reasons. We do it as of 3.3.1 to strip the `sourceMappingURL` from the files so that we can generate source maps for the whole vendor tree. `ember-popper` does it through `ember-cli-node-assets`, which I'm guessing is copying the module directory, rather than a specific file.
