### ISSUE TITLE
Popover is hidden on focusout when event='none'

### ISSUE THREAD

**Issue by mnoble01** [sir-dunxalot/ember-tooltips#362]
I'm running into an issue where interacting with a dropdown inside a popover causes the popover to be hidden.

The popover is being shown programmatically:
```hbs
{{#ember-popover
  event='none'
  isShown=showPopover
  popperContainer='body'
}}
  {{!-- content --}}
{{/ember-popover}}
```

This is what I think is happening:
- The dropdown inside the popover triggers a "focusout" event
- The "focusout" event propagates up to my component element, which is the popover target
- The "focusout" event is picked up by this ember-popover component listener - https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/components/ember-popover.js#L60-L64
- Because `popperContainer='body'` the mouse is not currently inside the target element and so the popover is hidden

This behavior is unexpected because I specifically set `event='none'`.

**Comment by maxfierke** [comment]
Thanks for investigating @mnoble01! I'll take a look at fixing this this week.
