### ISSUE TITLE
ember-tooltips 3.3.1+ build breaks w/ lazy engines

### ISSUE THREAD

**Issue by thec0keman** [sir-dunxalot/ember-tooltips#363]
Upgrading our application from 3.3.0 -> 3.3.2, and we're getting build failures:
```
  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, lstat '/var/folders/89/kt8fhhgx0pz0m3s5s588tkvc0000gn/T/broccoli-42794yLQNVhp1CiNT/out-016-broccoli_merge_trees_empty_merge_tree/vendor/ember-tooltips--popper.js'
```

Unfortunately I do not have time to dig into this more right now, but we do have an app with several lazy-load engines, and at least one does include `ember-tooltips`, so I suspect this may be the issue.

**Comment by maxfierke** [comment]
@thec0keman does the issue persist after `rm -rf dist tmp`?

**Comment by ecoutlee-hortau** [comment]
I got the same issue trying to upgrading from 3.3.0 to 3.3.3. The issue persist even after `rm -rf dist tmp`. I went back to version 3.3.0 because version 3.3.1 seem to still have the error.

**Comment by maxfierke** [comment]
@ecoutlee-hortau could you share a list of other ember addons you're using (or preferably your `package.json`, if you're able to share)? That might be useful for reproducing this.

**Comment by ecoutlee-hortau** [comment]
@maxfierke sure. It's with the .txt extension because Github don't allow me to upload a .json.
[package.txt](https://github.com/sir-dunxalot/ember-tooltips/files/3327320/package.txt)
 
The error message is a little different but seem similar enough to be the same issue:
`Build Error (Funnel)
ENOENT: no such file or directory, lstat '/home/ecoutlee/platform-webapp/tmp/funnel-input_base_path-BwXTIMfy.tmp/vendor/ember-tooltips--popper.js'`

**Comment by maxfierke** [comment]
Thanks! I see you're also using `ember-engines`. Are you also using lazy-loaded engines?

**Comment by ecoutlee-hortau** [comment]
Seem like we are using lazy-loaded engines.
Each engine have this line in their index.js:
`lazyLoading: process.env.IS_TESTING !== 'true',`

**Comment by thec0keman** [comment]
Sorry that I let this slip!

I'm seeing the same behavior after clearing `tmp` and `dist`.  We are also using engines.

**Comment by thec0keman** [comment]
Was able to trace things down to [this](https://github.com/sir-dunxalot/ember-tooltips/commit/87984d0152879ae8bc9cd58eb381751d259bbc08) commit.

**Comment by maxfierke** [comment]
I'll do some playing around with lazy engines this week to take a look at fixing this!

**Comment by maxfierke** [comment]
I think I traced it back to a recent change in how vendor trees are built in ember-engines (https://github.com/ember-engines/ember-engines/pull/646). There's some discussion on-going there about breakage in ember-cli-showdown, which is what ember-tooltips's `treeForVendor` implementation is based upon. I'll keep an eye on that thread for a bit, while I also try to figure out if there's a way to do what we want without using `treeForVendor`.

**Comment by alechirsch** [comment]
I am also running into this issue, using engines with lazy loading

**Comment by ecoutlee-hortau** [comment]
I just got a similar issue with ember-sortable. The owner pointed out it's probably related to ember-engines/ember-engines#400. Maybe it will help someone to find a solution to this issue.
