### ISSUE TITLE
added tooltip class when using popover component

### ISSUE THREAD

**Issue by mockey-jockey** [sir-dunxalot/ember-tooltips#367]
Added tooltip class when using popover component.

![image](https://user-images.githubusercontent.com/36475730/59992624-5ba8ce00-966a-11e9-98cd-303efdd3da44.png)

Here am facing the issue like when am using the ember popover ember tooltip class adding in dom

**Comment by maxfierke** [comment]
@mockey-jockey we spoke on Discord about this, but I'm not sure what the question is here? Could you provide some more detail?

**Comment by mockey-jockey** [comment]
`Template.hbs`

```
{{#ember-popover as |popover|}}
  Click <a href {{action 'hide' target=popover}}>here</a> to hide the popover
{{/ember-popover}}
```
 

and in the `DOM` is populating like this : 
![image](https://user-images.githubusercontent.com/36475730/60070564-c7f00400-9734-11e9-87b3-aa8a64279374.png)

In here am using `ember-popover` component then why `ember-tooltip` class added in dom elements. (`tooltip-arrow`, `tooltip-inner`)

**Comment by maxfierke** [comment]
@mockey-jockey those are just the default values for `arrowClass` and `innerClass`, but you can specify other values, if you wish, by passing them in to the component. We should probably use different classes by default for the popovers, to be honest.

https://github.com/sir-dunxalot/ember-tooltips/blob/86545c139ca34d2cf75b86eb8c649c9b66a68338/addon/components/ember-tooltip-base.js#L78-L79

**Comment by maxfierke** [comment]
I'm going to close this out for now, but if you have other questions about this, just reply to this issue and I'll re-open it.
