### ISSUE TITLE
ember-popover with an arrow

### ISSUE THREAD

**Issue by sylwiaeb** [sir-dunxalot/ember-tooltips#368]
Is there a way to render ember-popover with arrows, just like ember-tooltips?

**Comment by maxfierke** [comment]
@sylwiaeb Yup, popovers and tooltips are rendered the same, just with different CSS classes applied by default. Popover arrows are just not styled to be visible. You can checkout the [default CSS](https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/styles/addon.css) for what to override or you can add `arrowClass='my-popover-class-with-arrows'` to a popover to specify your own class to use for overriding the default styles.

**Comment by sylwiaeb** [comment]
@maxfierke Not sure yet which styles exactly need to override however when I tried with `arrowClass=tooltip-arrow ember-tooltip-arrow` the popover rendered with the arrow. I thought there's something else involved but I'll figure it out, thank you!
