### ISSUE TITLE
popover arrow style

### ISSUE THREAD

**Issue by luxferresum** [sir-dunxalot/ember-tooltips#369]
This is probably related to #368 

Currently we specify arrow styles in out [css](https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/styles/addon.css#L123) but in a way so its never ever applied.

Because of [that logic](https://github.com/sir-dunxalot/ember-tooltips/blob/b317eb1d80d0dc6458988e625396ba4aa1d2dd98/addon/components/ember-tooltip-base.js#L323) the arrow gets rendered with the style `ember-popover-arrow` not `ember-tooltip-arrow`.

However when we fix this things get interesting:
The arrow looks horrible. Its basically just white hiding the border there, not actually showing an arrow.

Shouldn't we either a) fix this or b) remove the arrow scoresheets for popovers altogether?

**Comment by andycochran** [comment]
This is addressed in #370.

**Comment by maxfierke** [comment]
#370 has been merged
