### ISSUE TITLE
Why do we need jQuery tests?

### ISSUE THREAD

**Issue by brookjordan** [sir-dunxalot/ember-tooltips#373]
Why do we need jQuery versions of tests still?
It was stated in #347 that it's for backward compatibility, but I'm not sure why removing the dependancy on jQuery would make anything incompatible?

The reason it came up is because we can't get onto Ember CLI yet due to technical reasons, so broccoli and so the build-time test file creation isn't an option for us.

**Comment by maxfierke** [comment]
We could remove them in a major version bump, but because there are jQuery-specific selectors that people might be using (e.g. `:contains()`), I don't want to do it in a 3.x release. The DOM helpers should still be accessible via `ember-tooltips/test-support/dom`, however.

**Comment by brookjordan** [comment]
@maxfierke Ah yes, I hadn't thought of that.
Ok cool, I'll stick with my `postinstall` script for now.

**Comment by brookjordan** [comment]
@maxfierke Ah yes, I hadn't thought of that.
Ok cool, I'll stick with my postinstall script for now.

**Comment by brookjordan** [comment]
As a post-note, although they're available through `/dom`, the code internals also point to that file, so I get errors inside of `ember-tooltips` itself.

I wonder if this is resolvable?

**Comment by maxfierke** [comment]
@brookjordan ran into that the other day actually with the jquery ones. I'll take a look at fixing the dom ones too tonight. Nice catch!

**Comment by maxfierke** [comment]
hmmm... looks like the DOM ones are already fixed. Mind giving master a try and if it's not workable, could you open a new issue for it? I can't promise a resolution for a build outside of ember-cli, but I'm willing to take a look.

**Comment by brookjordan** [comment]
Oh, ok, this works if I install straight from the commit 🎉 
When will the version get a bump so that I can install it naturally?

**Comment by maxfierke** [comment]
Tonight or tomorrow night
