### ISSUE TITLE
No way to specify the offset

### ISSUE THREAD

**Issue by luxferresum** [sir-dunxalot/ember-tooltips#376]
`popper.js` allows to specify an `offset` with the `offset` modifier.

With `ember-tooltips` however this is not possible, because [`tooltip.js` overwrites the `offset` property of any specified `offset` modifier](https://github.com/FezVrasta/popper.js/issues/812).

`tooltip.js` however allows the offset to be set independent of the modifiers. Because `ember-tooltips` however does not allow to set this `offset` property there is currently *no way* to specify the offset.

Either `tooltip.js` should not overwrite the `offset` modifier when no `offset` option is specified or `ember-tooltips` should allow to specify the `offset` option.

I'm not sure whats the way to go here. Maybe we should do both?

**Comment by maxfierke** [comment]
Thanks @luxferresum, looks like you were able to get fix in upstream, and this is included in popper.js v1.3.3 & v1.16.0
