### ISSUE TITLE
Having popover style the same as tooltip

### ISSUE THREAD

**Issue by slimee** [sir-dunxalot/ember-tooltips#379]
Hi,
Thanks you for this nice lib.

I would like to have all my popovers background-color in black, including the tooltip and the arrow, regardless the other options (position top/right/bottom/left for example)

How may I achieve this?
Best

**Comment by maxfierke** [comment]
Hi @slimee -- Thanks for asking. There's a great solution logged in #377 for now, which is the recommended way to do this: https://github.com/sir-dunxalot/ember-tooltips/issues/377#issuecomment-517076910

closing this issue in favor of #377

**Comment by slimee** [comment]
Thanks you max!
Very elegant.
