### ISSUE TITLE
Ember Tooltip v3.4.0 shows a tooltip outside the browser window

### ISSUE THREAD

**Issue by KhanhTranJBI** [sir-dunxalot/ember-tooltips#382]
Issue: I found is the tooltip shown and expand the browser window width and part of the tooltip content is hidden. 
![ember-tooltip-off-side](https://user-images.githubusercontent.com/5200117/66951217-bf3a7b00-f00e-11e9-8615-96fd34dafed7.gif)

Expected: I hope the tooltip will shown and does not expand the browser window width and the tooltip content is not hidden.

Thanks!

**Comment by maxfierke** [comment]
@KhanhTranJBI it looks like you may be using custom CSS to style the tooltips. Could you share that along with the context of how you're using the tooltip (e.g. a snippet of the handlebars template)?

**Comment by KhanhTranJBI** [comment]
@maxfierke yes, I am using a custom CSS. If I do not override CSS for tooltip then the tooltip width is around 50px which is too small and part of the tooltip is out of browser window screen.

Here is a component
```<span class="info-icon">&#61530;</span>
<EmberTooltip
  @onShow={{action "setContent"}}
  @updateFor={{this.content}}
  @side={{side}}
>
  {{#if this.content}}
    {{this.content}}
  {{else}}
    <div class="loading-spinner"></div>
  {{/if}}
</EmberTooltip>```

Here is a custom CSS
```.ember-tooltip {
  min-width: 200px;
  max-width: 316px;
  background-color: white;
  color: black;
  border: 1px solid green;
  text-shadow: none;

  .tooltip-inner {
    border: none;
    background-color: white;
    color: black;
  }

  .loading-spinner {
    @include loading-spinner();

    min-height: 10;
    min-width: 50;
  }
}```

**Comment by maxfierke** [comment]
@KhanhTranJBI is there any absolute or relative positioning on any of the parent elements?

**Comment by KhanhTranJBI** [comment]
@maxfierke yes, its parent elements has relative position as well as absolute position

Relative position on parent element
<img width="847" alt="Screen Shot 2019-10-16 at 1 02 23 PM" src="https://user-images.githubusercontent.com/5200117/66954447-45f25680-f015-11e9-8b6f-62179318e3ac.png">

Absolute position on other parent element
<img width="847" alt="Screen Shot 2019-10-16 at 1 03 28 PM" src="https://user-images.githubusercontent.com/5200117/66954549-7cc86c80-f015-11e9-9446-c3e32cfc7892.png">

**Comment by maxfierke** [comment]
Ahh, that may be what's causing issues with `popper.js`'s auto-placement. You may have luck passing `@popperContainer="body"` with your `<EmberTooltip>`, as that will position the tooltip relative to the `<body>` element.

**Comment by KhanhTranJBI** [comment]
@maxfierke It looks better, but the tooltip is still out of the browser window. Please check!
![ember-tooltip-off-side-after-add-proper](https://user-images.githubusercontent.com/5200117/66955445-2eb46880-f017-11e9-9908-d04194252dcb.gif)

**Comment by maxfierke** [comment]
@KhanhTranJBI I played around with this a bit, and this can be resolved by disabling a setting in popper.js that ember-tooltips enables by default, called `escapeWithReference` (more info here: in the [UPGRADING-3.x.md](https://github.com/sir-dunxalot/ember-tooltips/blob/959b57e37abfd25d9013206ab84e43de3d605bca/UPGRADING-3.x.md#my-tooltips-appear-clipped-use-within-elements-using-overflow-hidden))

```
<EmberTooltip
  @onShow={{action "setContent"}}
  @updateFor={{this.content}}
  @side={{side}}
  @popperOptions={{popperOptions}}
>
  {{#if this.content}}
    {{this.content}}
  {{else}}
    <div class="loading-spinner"></div>
  {{/if}}
</EmberTooltip>
```

where `popperOptions` is defined on the component as something like:

```javascript
{
  preventOverflow: {
    escapeWithReference: false
  }
}
```

**Comment by KhanhTranJBI** [comment]
@maxfierke It is the same. My coworker suggested me to use `@side="bottom-end"` which is good enough to solve the issue I have. Thank you so much @maxfierke!

**Comment by sotoyjuan** [comment]
> @KhanhTranJBI I played around with this a bit, and this can be resolved by disabling a setting in popper.js that ember-tooltips enables by default, called `escapeWithReference` (more info here in the [README.md](https://github.com/sir-dunxalot/ember-tooltips#popperoptions))
> 
> e.g.
> 
> ```
> <EmberTooltip @popperOptions={{popperOptions}}>
>   ...
> </EmberTooltip>
> ```
> 
> where `popperOptions` is defined on the component as something like:
> 
> ```js
> {
>   preventOverflow: {
>     escapeWithReference: false
>   }
> }
> ```

This solved the problem for me.
Thanks!
