### ISSUE TITLE
Can I use addon with handlebars?

### ISSUE THREAD

**Issue by vvscode** [sir-dunxalot/ember-tooltips#4]
Hi 

I try to use addon with ember 1.9.1 ( ember-cli 0.2.7 )
I try both
```
  "tooltips": {
    "setupInInitializer": true
  },
//and
  "tooltips": {
    "addTo": ["View", "Component"]
  },
```
do nothing. I even can't find addon's code at developing tools ( and that's strange - cause it means that files are not included ) ( Of course I restart my app on config changes )

Can you help?

Thx

**Comment by sir-dunxalot** [comment]
So you're placing the config in `config/environment.js`? And what happens when you remove the config entirely?

As a quick test could you also try adding version `0.1.1` to your package.json instead and then run `npm install`. Do you see the addon code then?

**Comment by sir-dunxalot** [comment]
I'm going to close this for now. Let me know if there are still issues persisting.
