### ISSUE TITLE
Tooltip made visible on focus even when event set to "manual"

### ISSUE THREAD

**Issue by arthur5005** [sir-dunxalot/ember-tooltips#40]
Hey, was a little perplexed as to why clicking on my target element was causing my tooltip visibility to toggle, given that I had set the visibility of the tooltip to manual.

After a combing through the code (very well written btw, great documentation) I found that ember-tooltips toggles visibility on focus for any event not set to "focus"; a little counter-intuitive, but the comment above made it clear that this was specifically for accessibility. 

https://github.com/sir-dunxalot/ember-tooltips/blob/43842d88435151fbdd68b5164076b76263e6bb29/addon/utils/render-tooltip.js#L196

While I think the intent is clear and fair, the primary use case for "manual" is to have explicit control for when a tooltip needs to be present and I think this undermines the use case. 

Might I suggest we change that line to:
```js
if (event !== 'focus' && event !=='manual' && event!=='none') {
```

**Comment by webark** [comment]
you could just move the focus and escape triggers up into the previous conditional.
```javascript
if (event !=='manual' && event!=='none')
```
I might submit a pull request for this.

**Comment by arthur5005** [comment]
Oh of course, that'd be a better option. 

If you won't, then I will tomorrow when I have a moment.

**Comment by sir-dunxalot** [comment]
Hey Arthur,

Good catch. I think this makes a lot of sense. I'll look at merging and releasing #41 this week. If there is a time crunch let me know.

**Comment by arthur5005** [comment]
No rush! 

We love ember-tooltips, we're looking to use them more extensively throughout our app, the manual control is really handy.

Warmest,
Arthur
