### ISSUE TITLE
Deprecation warnings with Ember 3.20

### ISSUE THREAD

**Issue by boris-petrov** [sir-dunxalot/ember-tooltips#402]
This addon uses `ember-maybe-in-element` [0.4.0](https://github.com/sir-dunxalot/ember-tooltips/blob/3.4.3/package.json#L39) which uses the as-of-Ember-3.20 deprecated `-in-element`. That's printed as warnings in the console when running `ember serve`. Simply updating `ember-maybe-in-element` to [1.0.0](https://github.com/DockYard/ember-maybe-in-element/releases/tag/v1.0.0) should fix the issue.

Thanks for the great addon!

**Comment by maxfierke** [comment]
Awesome, thanks for the heads up! Will take a look at that this week.

**Comment by raido** [comment]
@maxfierke any update on this?

**Comment by maxfierke** [comment]
@boris-petrov it was breaking CI for some earlier Ember versions, but will look at relaxing the constraint a bit tonight to allow for a greater range of versions

**Comment by raido** [comment]
The maybe-in-element addon has recent v2 release as well.

**Comment by maxfierke** [comment]
This has been addressed in v3.4.4
