### ISSUE TITLE
IE 11 - Not working due to js errors

### ISSUE THREAD

**Issue by thamsrang** [sir-dunxalot/ember-tooltips#412]
Hi,
There are JS error occurred in IE11 browser.
1. When tooltip creating.
Error occurred in `ember-tooltip-base.js` at line no. [407](https://github.com/sir-dunxalot/ember-tooltips/blob/6ef25b479f86f387fc4d2cc5535fee1ef7292e36/addon/components/ember-tooltip-base.js#L407)
```
Unhandled promise rejection TypeError: Unable to get property 'add' of undefined or null reference
```

2. When tooltip component destroying.
Error occurred in `ember-tooltip-base.js` at line no. [263](https://github.com/sir-dunxalot/ember-tooltips/blob/6ef25b479f86f387fc4d2cc5535fee1ef7292e36/addon/components/ember-tooltip-base.js#L263)
```
Unable to get property 'dispose' of undefined or null reference
```

**Comment by maxfierke** [comment]
@thamsrang IE 11 should support [classList](https://caniuse.com/classlist) just fine. I think these errors may indicate that the target of the tooltip (usually the parent element) doesn't exist by the time it does the setup for the tooltip. are you passing [`targetId`](https://github.com/sir-dunxalot/ember-tooltips#targetid) to the tooltip or moving it around the DOM somehow?

**Comment by maxfierke** [comment]
@thamsrang You need to make sure the element specified by `targetId` exists when the `<EmberTooltip>` is rendered

**Comment by maxfierke** [comment]
@thamsrang that's probably related to the first error where the tooltip wasn't able to attach itself to the target

**Comment by thamsrang** [comment]
Thanks for your comment. Working fine.
