### ISSUE TITLE
Do not add title

### ISSUE THREAD

**Issue by Gabiras12** [sir-dunxalot/ember-tooltips#42]
Hey, guys! Is it possible to ember-tooltips does not add the title attr? Or at least, do not show **two** tooltips. One styled and the default one.

**Comment by sir-dunxalot** [comment]
Hey, which version are you using? This should have been fixed yesterday with `0.5.8`.

**Comment by Gabiras12** [comment]
I was using `0.5.7`. Sorry about that. It's working now with `0.5.8`. Thanks!

**Comment by sir-dunxalot** [comment]
Awesome! I'm glad it worked.
