### ISSUE TITLE
Deprecation and fail on Addon => Addon

### ISSUE THREAD

**Issue by ksnyde** [sir-dunxalot/ember-tooltips#43]
I have an addon `ui-button` which I'd really like to use your addon for tooltips rather than Bootstrap's. I have added it to my template like this:

    <button type="button" class="ui-button btn btn-{{mood}} {{_size}}">
      {{#if hasBlock}}
        {{yield}}
      {{else}}
        <span class="content">
          {{#if tooltip}}
            {{#tooltip-on-parent}}{{tooltip}}{{/tooltip-on-parent}}
          {{/if}}
          {{#if icon}}
          <span class="icon">
            {{ui-icon icon=icon spin=iconSpin pulse=iconPulse}}
          </span>
          {{/if}}
          {{#if title}}
          <span class="title">
            {{title}}
          </span>
          {{/if}}
        </span>
      {{/if}}
    </button> 

However when add a tooltip I suddenly get two DEPRECATIONS (with rubbish debugging info):

![2016-02-08_14-52-43](https://cloud.githubusercontent.com/assets/980757/12889620/aeeb155a-ce77-11e5-9b00-088581430f67.png)

If I take it out of the conditional `{{#if}}` block then I get 15 deprecations of the same variety. Furthermore my tooltip does not display though I did check and the parent element and it does indeed have the `Tooltip` object attached and with a config that looks good to me:

![2016-02-08_15-25-01](https://cloud.githubusercontent.com/assets/980757/12889727/36c3be46-ce78-11e5-87a0-829d50358b61.png)

I think I can help with the DEPRECATIONS part, i'll send you a PR which I've already tested and it does indeed remove the deps. WRT, to the lack of a popup, however, I defer to your wisdom. Am I missing something?

**Comment by ksnyde** [comment]
Actually I can see that it is displaying the widget but at the upper left of the page (which was offscreen). I thought maybe it was compounded by the parent component having a `tagName` of `null` but I've changed it to a `span` and I get the same results.

**Comment by ksnyde** [comment]
If you're interested in seeing it in action take a look at the dummy app:

https://github.com/lifegadget/ui-button/tree/4c2809ee7b9b060e33bd18d81d6590ba7e512787

**Comment by ksnyde** [comment]
Ok, i'm narrowing it down. It's clear that `tagName: ''` breaks the selection. The reasons I thought it didn't work with `tagName: 'span'` was that I had a bad property value for `tooltipPlace` on my component.

**Comment by sir-dunxalot** [comment]
Hey Ken, thanks for the details and dummy app. I'll be sure to dig into this and I welcome the help!

Where are you passing the `tagName` property?

This might be averted by doing something like wrapping [this line](https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/components/tooltip-on-parent.js#L18) in a `Ember.run.scheduleOnce`. My theory is that the [renderTooltip](https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/mixins/components/tooltips.js#L118) is the culprit here.

**Comment by ksnyde** [comment]
You probably know but in later versions of Ember (not sure when it was introduced) asserting that `tagName: ''` in the component means that it doesn't automatically add an often unnecessary/unwanted element into the DOM and lets you paint to the DOM exclusively via the template. This appears to be the direction things are going in general so I think we'll see this pattern more and more.

Anyway, this means that the component itself is not in the DOM but it's templates elements are (that might not be entirely accurate but it's close).

**Comment by ksnyde** [comment]
I did try wrapping the line you suggested with `scheduleOnce` but get:

    You attempted to schedule an action in a queue (function () {
            parentView.renderTooltip(_this);
          }) that doesn't exist

**Comment by ksnyde** [comment]
Here's the transpiled code when I add the `scheduleOnce`:

      run.scheduleOnce('afterRender', function () {
            parentView.renderTooltip(_this);
       });

> Uncaught TypeError: Cannot read property 'innerHTML' of null

I doubt this will solve things as we're already in the 'afterRender' queue.

**Comment by ksnyde** [comment]
Damn. I'm pretty stumped. No problem having it work when the component has a `tagName` but I really want that cruft gone. Causes CSS problems, flexibility problems, or both. :)

**Comment by ksnyde** [comment]
https://github.com/lifegadget/ui-button/blob/5757dbf2c00b533ff3080c0577ce6fe87566d7f7/addon/components/ui-button.js#L13

Using my branch (to remove the deprecations), if `tagName` is set to "span" it works as it should. Set to an empty string it does not work.

**Comment by ksnyde** [comment]
I have to stop for now. Very interested in your thoughts once you've had a chance to look at it.

**Comment by sir-dunxalot** [comment]
Gotcha. So the `{{tooltip-on-parent}}` attaches a tooltip to the element of the parent component. If the parent component does not have an element in the DOM then the tooltip cannot attach itself anywhere. That is likely the conundrum here.

I do not know how to support attaching a tooltip to something that's no an element. Under the hood, this library uses https://github.com/darsain/tooltip, so there are some limitations with that library too.

Looking at your template, you could try the `tooltip-<x>` attributes. These let you add tooltips to an element that isn't an Ember component (e.g. `<span class="content">`). The downside of this approach is that the values of the attributes are not bound to the tooltip and, currently, the tooltip objects are not stored on the component. Thus, you would have to use an approach something like this (and we'd need to have `renderChildTooltips` resolve with the created tooltip objects:

```js
import Ember from 'ember';
import Tooltips from 'ember-tooltipx/mixins/components/tooltips';

export default Ember.Component.extend(
  Tooltips, {

  tooltipContent: null,
  tooltips: null,
  
  /**
  This alone would work if the tooltip content is not bound to an async property
  or does not change.

  @method didInsertElement
  */

  didInsertElement() {
    this.renderChildTooltips();
  },

  /**
  Something like this would be required if the tooltip content is changing.
  We would need to change renderChildTooltips() to support this kind of
  functionality.

  @method didReceiveAttrs
  */

  didReceiveAttrs() {
    if (this.get('tooltipContent')) {
      const tooltips = this.get('tooltips');

      if (tooltips) {
        tooltips.forEach((tooltip) => {
          tooltips.destroy(); // Remove tooltips is they exist with old content values
        });
      }

      this.renderChildTooltips().then((tooltips) => {
        this.set('tooltips', tooltips);
      });
    }
  },
});
```

Do you think this would work for your use case?

**Comment by ksnyde** [comment]
Considering it's a UI primitive I'm designing it would be nice to allow dynamic attributes. Let me mock up another approach and get your reaction to it. Also, regardless, would you consider accepting my PR as it does address the deprecation concern.

**Comment by ksnyde** [comment]
I've tried my alternate approach and it didn't work. Will work with your model. Am closing this but still hoping you'll approve PR.

**Comment by sir-dunxalot** [comment]
Yep, sorry it's just taking me a while to get to the PR. I'm planning on getting to it so we can merge.

This specific issue (data attribtues not updating) overlaps with #5, so let's track it there.

**Comment by ksnyde** [comment]
ok, heading over there now. btw, I do have a working solution now. I'll share it with you once I get to a good breaking point.

**Comment by sir-dunxalot** [comment]
Sounds good!
