### ISSUE TITLE
Deprecation warning: Using `run.bind` has been deprecated

### ISSUE THREAD

**Issue by jeroen-hoekstra** [sir-dunxalot/ember-tooltips#433]
We get this deprecation warning after updating to "ember-source": "3.27.1".
We use "ember-tooltips": "3.4.7".

```
DEPRECATION: Using `run.bind` has been deprecated. Instead, import the value directly from @ember/runloop:

import { bind } from '@ember/runloop'; [deprecation id: deprecated-run-loop-and-computed-dot-access]
```

https://github.com/sir-dunxalot/ember-tooltips/blob/ad7fc1aeaca34ac6b788eea0012ed9dcd29bca87/addon/components/ember-tooltip-base.js#L612

**Comment by maxfierke** [comment]
Thanks! I'll be doing a run at Ember 3.27+/4+ support in the coming weeks to address this
