### ISSUE TITLE
render-tooltip.js::setTooltipVisibility() Method Has Incorrect Logic

### ISSUE THREAD

**Issue by kkincade** [sir-dunxalot/ember-tooltips#54]
The first if statement has backwards logic. Currently it is...

`if (tooltip.hidden === shouldShow) {
    return;
 }`

...when it should be... 

`if (tooltip.hidden !== shouldShow) {
    return;
}`

This is not causing issues because the ember-tooltips mixin is setting hidden to an integer (i.e. 1) in the vendor/tooltip.js file, so the if statement is never true. However, if it were using the updated tooltip JS file from https://github.com/darsain/tooltip (where it is set to true), this logic will break because of the triple equals.

**Comment by sir-dunxalot** [comment]
Good catch. I will get this fixed soon.

On a related note, have you tried using this library with the updated Tooltip build? if so, did it work as intended?

**Comment by kkincade** [comment]
I forked ember-tooltips yesterday and modified a few things to suit my needs. I used the code from the updated Tooltip build and the demo app seems to work as intended. I haven't very thoroughly tested it, but all but two of the tests pass (not sure if those were because of my changes yet).

**Comment by sir-dunxalot** [comment]
This is no longer an issue with release `1.0.0`: https://github.com/sir-dunxalot/ember-tooltips/releases/tag/1.0.0
