### ISSUE TITLE
Deprecated sourcemap comments

### ISSUE THREAD

**Issue by dfreeman** [sir-dunxalot/ember-tooltips#59]
It looks like the files concatenated together into `vendor/tooltip/tooltip.js` contain a deprecated sigil for sourcemap comments (`@` vs `#`) which is producing the following warnings Chrome and similar ones in Firefox:

![image](https://cloud.githubusercontent.com/assets/108688/15196558/e4c33466-179a-11e6-9519-7a852f7cec6d.png)

Having read through https://github.com/darsain/tooltip/issues/28, it looks like the upstream author's stance amounts to:
> "I'm not going to work on this until someone magically fixes package management, and I'm also not going accept PRs either because everyone else should also refuse to do work until that happens."

😒 

Given that, would you consider just swapping in `#`s for the `@`s in the vendored file in this repo (or removing the comments entirely, since they don't actually point anywhere)?

**Comment by sir-dunxalot** [comment]
Agreed! I just have to merge #57 and this should be fixed.

**Comment by dfreeman** [comment]
D'oh. I only checked open issues, and didn't think to check if there was already a PR. Thanks!

**Comment by sir-dunxalot** [comment]
Fixed by #57
