### ISSUE TITLE
Make ember-tether a peer dependency

### ISSUE THREAD

**Issue by locks** [sir-dunxalot/ember-tooltips#60]
At the moment the `remove-vendor-css` branch breaks on render because `ember-tether` doesn't get installed. I believe that by making it a peer dependency that npm will warn the user to install it.
I could be wrong, who knows with npm sometimes ;P

**Comment by sir-dunxalot** [comment]
Fixed by commit a3911a4

**Comment by locks** [comment]
😁  sweet

**Comment by sir-dunxalot** [comment]
I've pushed a bunch of new code to that branch too. You'll see it change quite a bit over the next couple of days until I've got close to full-feature-parity with master branch (including tests). Let me know if you have any more questions about that branch!
