### ISSUE TITLE
v1.0 How to add tooltips to HTML

### ISSUE THREAD

**Issue by sukima** [sir-dunxalot/ember-tooltips#68]
In 0.6 I used `ember-tooltips/utils/render-tooltip` for my own custom component. It would parse text and render HTML which was injected through a computed property. I then used your `renderTooltip` using a jQuery `.each()`.

With 1.0 this concept was completely removed. How can we attach a tool tip to elements that were injected directly into the DOM?

Use case: Server sends text, Ember wishes to decorate the text so I compiles the text into HTML with `span` tags in it. Component then attaches the tooltip to each `span` tag after it being rendered into the template with `{{{compiledHtml}}}`:

```javascript
export default Ember.Component.extend({
  compiledHtml: Ember.computed('text', function() {
    return myCustomCompiler(this.get('text')).htmlSafe();
  }),
  didInsertElement() {
    this._super();
    this.$('span').each((index, el) => {
      renderTooltip(el, {…});
    });
  }
});
```

**Comment by sir-dunxalot** [comment]
The easiest way to add a tooltip to an element is using the `{{tooltip-on-element}}` component.

I imagine your component has some kind of `{{each}}` it's iterating on?

So perhaps something like this is what you are looking for:

```hbs
{{!--your-component.hbs--}}

{{#each arrayOfSpans as |span|}}
  <span>
    {{#tooltip-on-element  updateFor=span.compiledHtml}}
      {{{span.compiledHtml}}}
    {{/tooltip-on-element}}
  </span>
{{/each}}
```

If `compiledHtml` isn't retrieved asynchronously you don't need to use `updateFor`.

If that's not your approach, maybe you can show me some of your template so I better understand the use case?

**Comment by sukima** [comment]
I did something similar after talking on the Ember slacks. Instead of converting the text to HTML I converted it to an array of entities (read AST) the looped over them using key data in the entities to know if it was text or if a tool tip was needed.

**Comment by sir-dunxalot** [comment]
Ok, thanks for the tip! Let me know if you think there's a feature that could better support the use case.
