### ISSUE TITLE
Tooltip for input remains after action

### ISSUE THREAD

**Issue by jchamet** [sir-dunxalot/ember-tooltips#7]
I use ember liquid-fire which allows smooth transitions between routes. I have an action attached to input fields so that when a user presses the enter key within an input field, it takes them to a new route. 

Unfortunately, the old tooltip for the input field (that no longer is present) remains on the screen and requires a hard refresh to remove.

If there could be a way to trigger a tooltip clear on transition change, that would solve this issue.

**Comment by sir-dunxalot** [comment]
Hey James,

The issue could be caused by some interaction between liquid fire and ember-tooltips but I imagine we need a move stable way to clear tooltips across the board. For example:

```js
destroyTooltip: Ember.on('willDestroyElement', function() {
  const tooltip = this.get('tooltip');

  if (tooltip) {
    tooltip.detach();
  }
}),
```

Do you think that would solve the problem here?

**Comment by sir-dunxalot** [comment]
(And that code would be in the tooltip mixin).

**Comment by jchamet** [comment]
Your solution appears to work. Do you plan on committing this change to master?

**Comment by sir-dunxalot** [comment]
Yep, definitely. Not sure when though - I have a lot on my plate. I would be happy to accept a PR for an interim fix in the meantime (even if it doesn't add functionality for tooltips rendered using the `renderChildTooltip()` method.
