### ISSUE TITLE
Question: Positioning the pointer/arrow so it's not always centered

### ISSUE THREAD

**Issue by jwright04** [sir-dunxalot/ember-tooltips#71]
Awesome component.  Is it possible to position the pointer somewhere other than the center? Assuming I had a longer list, I'd prefer to have the arrow closer to the top of the tool tip box as opposed to the center.

**Comment by jwright04** [comment]
Actually looks like I figured it out, there is a pseudo :: after class that's set to 50%.

**Comment by sir-dunxalot** [comment]
So this could be a good feature to add eventually. Tether lets you set positions like 'left top' instead of 'left center.' I removed it for simplicity in the 1.0.0 release but it could be of added value in the future if more people have the use case of non-centered tooltips.
