### ISSUE TITLE
Visual issues with tooltips

### ISSUE THREAD

**Issue by hoboman313** [sir-dunxalot/ember-tooltips#72]
First off, this addon looks very promising and is much easier to use with ember than something like bootstrap tooltips. Secondly...I ran into a bunch of visual issues that I was hoping I could get some help with. I hope it's okay that I list several issues here.

1.)  keepInWindow doesn't actually try to keep the tooltip inside the window...or maybe it just doesn't try as hard as the bootstrap tooltip addon?
An example: When I resize the window, the tooltip doesn't get resized to try to fit in. <a href="http://imgur.com/KRco44M"><img src="http://i.imgur.com/KRco44M.png" title="source: imgur.com" /></a>
If you look at the bootstrap example ( http://getbootstrap.com/javascript/#tooltips ) while resizing the page, you'll notice that the tooltip overflows to multiple lines and it does a pretty good job, to a certain extent, to stay inside the window.

2.) ember-tooltips don't get re-rendered between model changes
I've noticed that ember-tooltips always display well after I transition between different routes. However, in the case that I stay on the same route and substitute in different models, the tooltips stop showing up all together.
^ I hope this was descriptive enough. I think what I'm looking for is a functionality to force the ember-tooltips to re-init themselves.

3.) ember-tooltips don't always get displayed under the correct element even when setting a target
Consider the block like
`{{#if yelpData.haveReviews}}
                    <a id="yelp-anchor" href="{{yelpData.url}}" target="_blank" rel="noopener noreferrer">
                      <img src="{{yelpData.rating_img_url_large}}" id="yelp-rating" />
                    </a>
                    {{#tooltip-on-element class="ember-tooltip" target="#yelp-anchor"}}{{yelpData.rating}} based on {{yelpData.review_count}} reviews{{/tooltip-on-element}}
                  {{/if}}`

where the tooltip is attached to #yelp-anchor. When I hover over the element the tooltip correctly comes up, but its position is way off.
<a href="http://imgur.com/jZHmxlY"><img src="http://i.imgur.com/jZHmxlY.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/P4wPeWo"><img src="http://i.imgur.com/P4wPeWo.png" title="source: imgur.com" /></a>
Any help debugging this would be appreciated

**Comment by sir-dunxalot** [comment]
Hi Egor, thanks for the details!

1) It would appear that the `resize` and `onscroll` events aren't being tracked by [Tether](https://github.com/HubSpot/tether) as they should. Perhaps they're getting overridden in [ember-tether](https://github.com/yapplabs/ember-tether)

2) Did you see the `updateFor` property? You could do something like:

```hbs
{{tooltip-on-parent updateFor=model}}
  This tooltip should rerender when model changes
{{/tooltip-on-parent}}
```

Or is that not what you're looking for? Maybe there are larger performance implications here?

3) Could this be related to #69?

**Comment by andrew-zenefits** [comment]
@hoboman313 did you happen to find a solution for #3? I've come across the same problem.

**Comment by hoboman313** [comment]
@andrew-zenefits Nope.

**Comment by msmyers** [comment]
This is reproduced when having a custom Ember.APP.rootElement definition.

This is because Ember does not listen to events for divs that are located outside of the rootElement.

It would seem that the tooltip div is always the first-child of the body, which would be incorrect in this case.

**Comment by knownasilya** [comment]
I have an issue like number 1, but I don't actually resize the window. The tooltip just renders outside of the edge of the window:

![screen shot 2016-11-22 at 3 54 20 pm](https://cloud.githubusercontent.com/assets/34726/20541603/fa0c4dce-b0cb-11e6-8d7f-4633dcbfdadf.png)

**Comment by nagits** [comment]
@hoboman313 > 1.) keepInWindow doesn't actually try to keep the tooltip inside the window.
@knownasilya > The tooltip just renders outside of the edge of the window:

@sir-dunxalot Adding `pin: true` to https://github.com/sir-dunxalot/ember-tooltips/blob/2e01e9e59cc175226e0fc638ac4d185522c4795a/addon/components/tether-tooltip-and-popover.js#L183 fixes this.

**Comment by DavidPhilip** [comment]
@nagits I would love to see a PR for this either as a default or another option you can set. Can you manage to do one please?
