### ISSUE TITLE
Wrong positioning when attaching tooltips to elements inside table cells

### ISSUE THREAD

**Issue by ChrizzDF** [sir-dunxalot/ember-tooltips#75]
Hi guys,

First of all, thanks for this cool addon. Really easy to use unlike other addons I tried before.
I don't know if this really is an issue or a feature request, but I hope it's okay anyway.

My problem:
I'm rendering a table (100% width) with a varying amount of cells inside. Let's assume I have 5 cells and in each cell there is a `{{#tooltip-on-element ...}}` attached to an element.
As each row starts to render the cells one by one, the cells are growing after the tooltip inside was already rendered, so they are slightly moved to the side. If a resize the window, repositioning is taking effect and everything is fine.

Does anybody has a solution for this problem that comes out of the box?

Thanks in advance for having a look at my message! =)

**Comment by sir-dunxalot** [comment]
Thanks for the kind words and for opening the issue.

I think this is an issue and my guess would be that it's sharing something with #72 and #69. These issues arose after the 1.0.0 release, which uses Ember Tether under the hood.

The trend seems to be that resizing the window fixes these issues and, therefore, it seems like a certain method might not be getting called when the target the tooltip is attached to renders.

I don't have a workaround off the top of my head but definitely would like to fix this issue. The start point seems to be figuring out what methods are called on resize.

**Comment by ChrizzDF** [comment]
Thanks for taking this bug in!
I also try to have a look at it.

**Comment by andrew-zenefits** [comment]
@ChrizzDF did you happen to find a solution for this? I've come across the same problem.

**Comment by andrew-zenefits** [comment]
@ChrizzDF and @sir-dunxalot I found *a* solution. We need to make sure that the tooltip is correctly positioned anytime a user hovers over the target element. To do this I added this code at the beginning of the `show()` function...

```
this.positionTether();
// this._tether.position(); // if you're on an older version of ember-tether like we are
```

This has fixed the bug for us in every use case we've seen it. Duncan do you think this is an appropriate fix to make a PR for?

**Comment by sir-dunxalot** [comment]
Good work, Andrew. Given that we haven't identified anything more reliable and this covers all of your use cases, it sounds more than good enough for a PR. Whilst I am a little weary of using a private API, I think it's more important to deliver the correct UX right now. Would you agree?

**Comment by ChrizzDF** [comment]
Hey, sorry for not responding in time...
No, we've had our focus on other things in the meantime so I'm very glad that you found a promising solution! I'd love to see you merge this fix into master 😎

**Comment by a15n** [comment]
@sir-dunxalot here is the fix https://github.com/sir-dunxalot/ember-tooltips/pull/83

Note that it doesn't include any private api. `ember-tether0.3.1` has the method `positionTether`. I only mentioned the private API approach because the version of tether that Zenefits uses doesn't have `positionTether`. I guess it's not relevant information because we have created our own branch to support our current version of ember-tether.

**Comment by sir-dunxalot** [comment]
Ah, gotcha. We'll get #83 merged and released.
