### ISSUE TITLE
Ember-tooltips.css.map is missing

### ISSUE THREAD

**Issue by Deovandski** [sir-dunxalot/ember-tooltips#76]
Has anyone else came across this issue where something is requesting for **/assets/ember-tooltips.css.map**? I am using Ember-cli-rails by the way.

```
Started GET "/assets/ember-tooltips.css.map" for 127.0.0.1 at 2016-06-08 02:14:41 -0500
02:14:41 web.1  | 
02:14:41 web.1  | ActionController::RoutingError (No route matches [GET] "/assets/ember-tooltips.css.map"):
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/show_exceptions.rb:30:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:38:in `call_app'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `block in call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `block in tagged'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:26:in `tagged'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/active_support/tagged_logging.rb:68:in `tagged'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rails/rack/logger.rb:20:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/request_id.rb:21:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rack/methodoverride.rb:22:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rack/runtime.rb:18:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rack/lock.rb:17:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/static.rb:120:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rack/sendfile.rb:113:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rails/engine.rb:518:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rails/application.rb:165:in `call'
02:14:41 web.1  |   /usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
02:14:41 web.1  |   puma (3.4.0) lib/puma/configuration.rb:224:in `call'
02:14:41 web.1  |   puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
02:14:41 web.1  |   puma (3.4.0) lib/puma/server.rb:406:in `process_client'
02:14:41 web.1  |   puma (3.4.0) lib/puma/server.rb:271:in `block in run'
02:14:41 web.1  |   puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'
02:14:41 web.1  | 
02:14:41 web.1  | 
02:14:41 web.1  |   Rendered /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/templates/rescues/_trace.html.erb (0.9ms)
02:14:41 web.1  |   Rendered /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/templates/routes/_route.html.erb (4.2ms)
02:14:41 web.1  |   Rendered /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/templates/routes/_table.html.erb (6.1ms)
02:14:41 web.1  |   Rendered /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
02:14:41 web.1  |   Rendered /usr/lib/ruby/vendor_ruby/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (40.1ms)
```

Let me know if there is any other information I can provide! Also, the Source Code is open source, and accessible at [Deovandski/Fakktion](https://github.com/Deovandski/Fakktion)

**Comment by ludalex** [comment]
Yup, happened to me as well, now living w/ it as it doesn't really break anything and it's hard to find the cause.
Tried some debugging, came to the conclusion that something broke with babel asset pipeline compilation. 
Worth looking, maybe related: https://github.com/joliss/broccoli-sass/issues/39, https://github.com/aexmachina/ember-cli-sass/issues/84

**Comment by Deovandski** [comment]
It does seem to be what you suggested... Since it is not an issue that actually alter the program expectations. I will leave it to be as well.

Now regarding your suggestion, I sense that you have an assumption that non-unified projects is always the solution instead of using unified workflow like ember-cli-rails, but let me tell from experience that both methodologies have its strengths and optimum implementation scenario, and being able to manage an entire application through one central point is definitely one for Ember-cli-rails (especially since I am the sole maintainer of Fakktion which makes managing the Ubuntu server through scripts a straight forward process.)

**Comment by musaffa** [comment]
@sir-dunxalot I'm getting this error when I do `ember serve --proxy [proxy_url]`. The issue may be related to `ember-cli-sass`. How about removing `ember-cli-sass` dependency and providing pure css file?

**Comment by sir-dunxalot** [comment]
I've had this issue appear in other projects as well (unrelated to ember tooltips). There is an issue upstream. Removing ember-cli-sass could be an option but the CSS is already pretty hard to maintain and it could get more complex with the addition of popovers. I wonder if we can just disable requesting source maps?

**Comment by ADTC** [comment]
Is there a way to disable requesting source map? This was ignored in our project until we applied [this fix to make sure we don't get an error upon refreshing page](https://stackoverflow.com/questions/43851499). However, this caused the project to have critical problems because of the 404 on CSS source map file - now the 404 instead of sending 404 error, redirects to the index page, which causes the source map request to fail spectacularly. Functionality was reduced, and browser memory leaks occur.
