### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by JoshSmith** [sir-dunxalot/ember-tooltips#86]
Hey, sorry for the drive-by issue opening! Thanks a lot for taking the time to build this addon and put in all the hard work of maintaining it.

I was wondering if you wouldn't mind adding a CHANGELOG.md and document some of the changes? It took me a little time to work through where to find the 2.0.0 release (not in a PR, a separate commit) and the changes associated with it. 2.0.0 is a big bump so some documentation around it would be good.

You can then suggest that new changes to the code base require a corresponding change to the CHANGELOG, and then you can accumulate and reorganize those when you publish releases.

I wish I had time to help more on this issue, so apologies again for making a request for _more_ of your time without helping personally. Feel free to reject this request, but thought it might help!

**Comment by sir-dunxalot** [comment]
Hey, no problem - appreciate the feedback. it's a good point to bring up!

I like the idea of requiring an addition to the changelog with PRs.

I've always added release notes to the releases tab, when necessary. Do you think that's enough or do you think the changelog needs to exist beside that?

**Comment by JoshSmith** [comment]
@sir-dunxalot I honestly didn't even notice it. Maybe mentioning in the documentation would be a good first step, and you could circle back to a changelog later?

**Comment by JoshSmith** [comment]
Also just the README mentioning the 1.0.0 release was confusing me a bit, so I thought that maybe you were using the README as a sort of changelog proxy.

**Comment by sir-dunxalot** [comment]
Got it. That all makes a lot of sense. I think a change log will be the most long-term-reliable solution here. I'll see if I can find some time over the next week or two to implement it.

**Comment by sir-dunxalot** [comment]
For now, we're making the release log more explicit and descriptive. This should act just like a change log.
