### ISSUE TITLE
More options for the "side" parameter

### ISSUE THREAD

**Issue by Juggle4Evr** [sir-dunxalot/ember-tooltips#88]
Hi,

as the "keepInWindow" paramete doesn't work very reliable, how about implementing some more options for the "side" parameter? Something like "bottomleft", "bottomright" etc.
This way it would be possible to position the tooltip inside the window so that it should be completely visible in most cases.

**Comment by andrew-zenefits** [comment]
This is being considered here https://github.com/sir-dunxalot/ember-tooltips/issues/82

**Comment by sir-dunxalot** [comment]
I'll mark this as a duplicate for #82 but it's a great idea that we fully plan on implementing.
