### ISSUE TITLE
renderTooltip equivalent in 2.x?

### ISSUE THREAD

**Issue by jamesdixon** [sir-dunxalot/ember-tooltips#91]
Hi,

We were using 0.5.9 and just upgraded and found that `renderTooltip` is no longer available. Is there an equivalent in 2.x? We're using the tooltips for event in FullCalendar, so there is no handlebars template for us to work with; we need an the option to use it programmatically.

Thanks for your hard work!

**Comment by sir-dunxalot** [comment]
Hi James,

Currently there is no equivalent method to programmatically create tooltips. This was removed to standardize the options for creating tooltips whilst staying within Ember's conventions (components, real handlebars bindings, run loops, etc).

There are ways to render Ember components on the fly. If you research those methods and find one that works for you then that might be a good solution.

This request has come up in the past. As such, I'd be open to a PR that adds this kind of functionality. However, I suspect this will be a hacky implementation and not an Emberish implementation.

Sorry there isn't an easier solution right now.

**Comment by jamesdixon** [comment]
Thank you for the quick reply!

**Comment by jamesdixon** [comment]
@sir-dunxalot is this now possible again with the 3.x branch?

**Comment by sir-dunxalot** [comment]
Hi James,

Unfortunately, this util does not exist in the 3.x branch. However, it is functionality we may be able to support again in the future. Is your request still related to the FullCalendar use case?

**Comment by jamesdixon** [comment]
@sir-dunxalot correct! For now, I'm just manually instantiating the tooltip given that the Popper library is already loaded. Thanks!
