### ISSUE TITLE
How to prevent tooltips from being created on mobile

### ISSUE THREAD

**Issue by ianpetzer** [sir-dunxalot/ember-tooltips#95]
Hi there,

I'm just upgrading from version 0.7. Really enjoying what you've done with version 2! Feels so much more ember-y :)

We're using a number of tooltips that show on hover. Previously in v0.7, I was using the mixin and just wouldn't render the tooltips on mobile, but I was just wondering how I could set all of the tooltips not to show on mobile?

Is there something I could do to stop all tooltips from being created in mobile  (my app knows when it is mobile) other than wrapping all of the {{#tooltip-on-element}} in {{#if}} blocks?

Maybe by extending the tooltip component?

**Comment by sir-dunxalot** [comment]
The easiest solution would be to hide the tooltips using CSS and media queries. If you wanted to prevent the tooltips from rendering you could extend the tooltip component and overwrite [show()](https://github.com/sir-dunxalot/ember-tooltips/blob/master/addon/components/tooltip-on-element.js#L386).

You could also programmatically change the `showOn` param for mobile devices. Something like [ember-resize](https://www.npmjs.com/package/ember-resize) might help.

Hopefully that helps. I'm going to close this as a library issue but feel free to keep the conversation going on here!
