### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by lvl99** [sir-dunxalot/ember-tooltips#99]
I've added tooltips to my Ember app and it's slowed the whole thing down immensely.

Is it possible to remove/destroy the tooltip element when it is hidden?

**Comment by sir-dunxalot** [comment]
It seems like this issue has gotten progressively worse. Obviously, we shouldn't be affecting app performance in any noticeable way. #96 introduces some improvements here, as you've seen. Let's see if that is the fix you need. If it's still slow, we'll need to do some serious digging.

**Comment by sir-dunxalot** [comment]
#96 has been released as `2.3.1` - see if this fixes the performance issues you're seeing.

**Comment by a15n** [comment]
@lvl99 if https://github.com/sir-dunxalot/ember-tooltips/pull/96 has fixed the slowness after the page has loaded but you're still experiencing slowness on initial render you should check out https://github.com/sir-dunxalot/ember-tooltips/issues/100

**Comment by lvl99** [comment]
I applied the new version (2.3.1) and uncommented my code to get the tooltips running again. Seems that it isn't outputting my `i18n` strings in the tooltips. It was just a quick test while I was working on some other stuff, so I haven't been able to put any time into it yet, sorry.

**Comment by lvl99** [comment]
I've updated to the latest version (`2.4.2`). It all seems to work pretty well. Looking forward to the `enableLazyLoading` being set `true` to default!

Thanks to @sir-dunxalot and @a15n for your quick and responsive comments and work.

**Comment by a15n** [comment]
Glad things are working. We're planning on setting that to `true` by default in 3.0.0

Here is the ticket with things we need to accomplish before that release

https://github.com/sir-dunxalot/ember-tooltips/issues/109
